## We will use NLP for text analytics.
## Natural Language Processing (NLP) is a field of AI that enables computers to understand, interpret, and generate human language.
Typical NLP tasks:
1. Tokenization
2. Vocabulary
3. Bag of Words concept
4. CountVectorizer
5. TF-IDF
6. Word Embeddings
NLP Pipeline (Where Modeling Fits)

1. Text Cleaning (removing punctuations, lowercasing)
2. Tokenization
3. Stopword Removal
4. Stemming/Lemmatization
5. Feature Extraction (like TF-IDF, Word2Vec)
6. MODELING (training a model to make predictions)
7. Evaluation

Library	Use case

*NLTK*	
:Classical NLP (tokenization, stemming, POS)

*SpaCy*	
:Fast, production-grade NLP pipelines

*Hugging Face* 
:Deep learning NLP (BERT, GPT, etc.)

*TextBlob*	
:Simple sentiment analysis, translation

*Gensim*	
:Topic modeling, word embeddings

# NLTK USES 

Feature	NLTK Functionality
*Tokenization*:               word_tokenize(), sent_tokenize()
*Stemming*:	                PorterStemmer, LancasterStemmer
*Lemmatization*:	            WordNetLemmatizer
*Stopword Removal*:        	nltk.corpus.stopwords
*POS Tagging*:             	pos_tag()
*Named Entity Recognition*:	ne_chunk()
*Chunking*:	                RegexpParser()
*Corpora Access*:	            nltk.corpus.<name>
*Text Classification*:        nltk.NaiveBayesClassifier, etc.
*POS Tagging*:             	pos_tag()
*NP Chunking*:	                RegexpParser + POS patterns

In [1]:
sentence = "We are Learning TextMining from 360DigiTMG"
words=sentence.split()
words

['We', 'are', 'Learning', 'TextMining', 'from', '360DigiTMG']

In [3]:
# print the words with even length
eve=[i for i in words if len(i)%2 != 0] #print those words whose len is odd
eve

['are']

In [4]:
# print the words with even in the index
eve=[words[i] for i in range (len(words)) if i%2 == 0]
eve

['We', 'Learning', 'from']

# word Tokenization
# Tokenizer	Use When You Want To...
# word_tokenize()	Tokenize regular text into words (default choice)
# sent_tokenize()	This function splits a paragraph into a list of individual sentences. It uses an algorithm called the Punkt Sentence Tokenizer
# TweetTokenizer	Tokenize tweets, emojis, hashtags, mentions
# RegexpTokenizer	Custom rules like removing punctuation
# MWETokenizer	Treat multi-word expressions as a single token
# WhitespaceTokenizer	Just split by spaces (very simple)

In [10]:
import nltk
#nltk.download('all')

In [11]:
# there are 2 type of tokenization word_tokenize and sent_tokenize
from nltk.tokenize import word_tokenize, sent_tokenize
words = word_tokenize("I! am reading NLP Fundamentals")
print(words)


data = "India (Hindi: Bhārat), officially the Republic of India the second-most populous country, and the most populous democracy in the world. Bounded by  and Nicobar Islands share a maritime border with Thailand and Indonesia."
#so before we get on clean data we can also use replace in case i want to replace it with specific word
normalized_sentence =data.replace("MY", "Malaysia").replace("IND", "India").replace("-20", "-2020")
print(normalized_sentence)


st=nltk.sent_tokenize(normalized_sentence)
print(st)

['I', '!', 'am', 'reading', 'NLP', 'Fundamentals']
India (Hindi: Bhārat), officially the Republic of India the second-most populous country, and the most populous democracy in the world. Bounded by  and Nicobar Islands share a maritime border with Thailand and Indonesia.
['India (Hindi: Bhārat), officially the Republic of India the second-most populous country, and the most populous democracy in the world.', 'Bounded by  and Nicobar Islands share a maritime border with Thailand and Indonesia.']

In [12]:
from nltk.tokenize import word_tokenize, MWETokenizer

# Example text
text = "I went to New York and studied machine learning . New Delhi is the national capital of india"

# Define phrases to join (multi-word expressions)
mwe_phrases = [('New', 'York'), ('machine', 'learning'),('New','Delhi')]

# Create a tokenizer that joins these phrases
tokenizer = MWETokenizer(mwe_phrases, separator='_')

# Tokenize the text into words
basic_tokens = word_tokenize(text)

# Apply the MWE tokenizer
tokens_with_mwe = tokenizer.tokenize(basic_tokens)

# Print result
print(tokens_with_mwe)

['I', 'went', 'to', 'New_York', 'and', 'studied', 'machine_learning', '.', 'New_Delhi', 'is', 'the', 'national', 'capital', 'of', 'india']

In [13]:
text='hi there is a place I went to New York and studied machine learning. New Delhi is the national capital of india'
my_parser=[('New' ,'York'), ('machine', 'learning'),('New','Delhi')]
mwe_token=MWETokenizer(my_parser, separator='_')
word_token=word_tokenize(text)

token_with_MWE=mwe_token.tokenize(word_token)
print(token_with_MWE)

['hi', 'there', 'is', 'a', 'place', 'I', 'went', 'to', 'New_York', 'and', 'studied', 'machine_learning', '.', 'New_Delhi', 'is', 'the', 'national', 'capital', 'of', 'india']

# ==================POLARIZATION=========================
In the context of TextBlob and Sentiment Analysis, Polarity is a numerical value that represents the emotional orientation of a piece of text.

In [179]:
from textblob import TextBlob


long_text = '''This is a great product. 
I am very disappointed. India (Hindi: Bhārat), officially the Republic of India the second-most populous country'''
individual_sentences = sent_tokenize(long_text) # This is sentence tokenization
for s in individual_sentences:
    print(s)
    # VADER or TextBlob here, directly on 's'
    blob = TextBlob(s)
    polarity = blob.sentiment.polarity
    print(polarity)
    # Optional: Interpret the polarity for easier understanding
    if polarity > 0:
        sentiment_label = "Positive"
    elif polarity < 0:
        sentiment_label = "Negative"
    else:
        sentiment_label = "Neutral"
    print(f"  Sentiment Label: {sentiment_label}\n")

This is a great product.
0.8
  Sentiment Label: Positive

I am very disappointed.
-0.9750000000000001
  Sentiment Label: Negative

India (Hindi: Bhārat), officially the Republic of India the second-most populous country
0.0
  Sentiment Label: Neutral

# POS Tagging

In [27]:
import nltk
#nltk.download('tagsets')
# Show all POS tags with meanings
nltk.help.upenn_tagset()

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
JJR: adjective, comparative
    bleaker braver breezier briefer brighter brisker broader bumper busier
    calmer cheaper choosier cleaner clearer closer colder commoner costlier
    cozier creamier crunchier cuter ...
JJS: adjective, superlative
    calmest cheapest choicest classiest cleanest clearest closest commonest
    corniest costliest crassest creepiest crudest cutest darkest deadliest
    dearest deepest densest dinkiest ...
LS: list item marker
    A A. B B. C C. D E F First G H I J K One SP-44001 SP-44002 SP-44005
    SP-44007 Second Third Three Two * a b c d first five four one six three
    two
MD: modal auxiliary
    can cannot could couldn't dare may might must need ought shall should
    shouldn't will would
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...
NNPS: noun, proper, plural
    Americans Americas Amharas Amityvilles Amusements Anarcho-Syndicalists
    Andalusians Andes Andruses Angels Animals Anthony Antilles Antiques
    Apache Apaches Apocrypha ...
NNS: noun, common, plural
    undergraduates scotches bric-a-brac products bodyguards facets coasts
    divestitures storehouses designs clubs fragrances averages
    subjectivists apprehensions muses factory-jobs ...
PDT: pre-determiner
    all both half many quite such sure this
POS: genitive marker
    ' 's
PRP: pronoun, personal
    hers herself him himself hisself it itself me myself one oneself ours
    ourselves ownself self she thee theirs them themselves they thou thy us
PRP$: pronoun, possessive
    her his mine my our ours their thy your
RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
RBR: adverb, comparative
    further gloomier grander graver greater grimmer harder harsher
    healthier heavier higher however larger later leaner lengthier less-
    perfectly lesser lonelier longer louder lower more ...
RBS: adverb, superlative
    best biggest bluntest earliest farthest first furthest hardest
    heartiest highest largest least less most nearest second tightest worst
RP: particle
    aboard about across along apart around aside at away back before behind
    by crop down ever fast for forth from go high i.e. in into just later
    low more off on open out over per pie raising start teeth that through
    under unto up up-pp upon whole with you
SYM: symbol
    % & ' '' ''. ) ). * + ,. < = > @ A[fj] U.S U.S.S.R * ** ***
TO: "to" as preposition or infinitive marker
    to
UH: interjection
    Goodbye Goody Gosh Wow Jeepers Jee-sus Hubba Hey Kee-reist Oops amen
    huh howdy uh dammit whammo shucks heck anyways whodunnit honey golly
    man baby diddle hush sonuvabitch ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...
VBD: verb, past tense
    dipped pleaded swiped regummed soaked tidied convened halted registered
    cushioned exacted snubbed strode aimed adopted belied figgered
    speculated wore appreciated contemplated ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
VBN: verb, past participle
    multihulled dilapidated aerosolized chaired languished panelized used
    experimented flourished imitated reunifed factored condensed sheared
    unsettled primed dubbed desired ...
VBP: verb, present tense, not 3rd person singular
    predominate wrap resort sue twist spill cure lengthen brush terminate
    appear tend stray glisten obtain comprise detest tease attract
    emphasize mold postpone sever return wag ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
WDT: WH-determiner
    that what whatever which whichever
WP: WH-pronoun
    that what whatever whatsoever which who whom whosoever
WP$: WH-pronoun, possessive
    whose
WRB: Wh-adverb
    how however whence whenever where whereby whereever wherein whereof why
``: opening quotation mark
    ` ``

In [28]:
import nltk
word_pos_tagging=nltk.pos_tag(words)
sent_pos_tagging=nltk.pos_tag(st)
print(word_pos_tagging)
print("sent_pos_tagging",sent_pos_tagging)

[('I', 'PRP'), ('!', '.'), ('am', 'VBP'), ('reading', 'VBG'), ('NLP', 'NNP'), ('Fundamentals', 'NNS')]
sent_pos_tagging [('India (Hindi: Bhārat), officially the Republic of India the second-most populous country, and the most populous democracy in the world.', 'JJ'), ('Bounded by  and Nicobar Islands share a maritime border with Thailand and Indonesia.', 'NNP')]

# Chunking = Grouping words into phrases based on their POS tags.

* * After using parts of speech, chunking can be used to make data more structured by giving a specific set of rules. Chunking is also known as a shallow parser. 
Let's understand more about chunking by following this example

In [30]:
import nltk
stre = "India (Hindi: Bhārat), officiall the north; and Bangladesh"
data=nltk.word_tokenize(stre)
pos_tagged_data=nltk.pos_tag(data)


my_node = "MN: {<NNP>+<NN>*}"
#Start with one or more Proper Nouns (<NNP>+)

#Optionally followed by zero or more Singular Nouns (<NN>*)

chunk=nltk.RegexpParser(my_node)

result = chunk.parse(pos_tagged_data)
print(list(result))
print(result)
#result.draw()    # It will draw the pattern graphically which can be seen in Noun Phrase chunking

[Tree('MN', [('India', 'NNP')]), ('(', '('), Tree('MN', [('Hindi', 'NNP')]), (':', ':'), Tree('MN', [('Bhārat', 'NNP')]), (')', ')'), (',', ','), ('officiall', 'PDT'), ('the', 'DT'), ('north', 'NN'), (';', ':'), ('and', 'CC'), Tree('MN', [('Bangladesh', 'NNP')])]
(S
  (MN India/NNP)
  (/(
  (MN Hindi/NNP)
  :/:
  (MN Bhārat/NNP)
  )/)
  ,/,
  officiall/PDT
  the/DT
  north/NN
  ;/:
  and/CC
  (MN Bangladesh/NNP))

## Stop Word

## Stop Words
Stop words are such words which are very common in occurrence such as ‘a’,’an’,’the’, ‘at’ etc. Yes — different NLP libraries 
(like 
1.NLTK,
2.spaCy,
3.Scikit-learn, etc.) 
have their own lists of stopwords. This means:

✅ They don’t all use the same words
✅ Some include more words, some fewer
✅ This affects your text analysis (like TF-IDF, sentiment, etc.)

You want to remove as much “noise” as possible

In [38]:
#nltk.download('stopwords')  # Stop Words from nltk library
import nltk
from nltk.corpus import stopwords

stop_words = stopwords.words('English') # 179 pre defined stop words
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [39]:
#!pip install spacy

In [40]:
#!conda install numpy=1.26.4 h5py spacy

In [41]:
#import spacy
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

print(list(STOP_WORDS))  # About 326 words

['eleven', 'very', 'few', 'several', 'amount', 'a', 'at', 'indeed', 'about', 'used', 'anyway', 'since', 'over', 'within', 'its', 'the', 'she', 'thus', 'ten', 'might', 'what', 'less', 'too', 'go', 'of', 'which', 'had', 'moreover', 'next', 'here', 'others', 'move', 'same', 'n‘t', 'ever', 'third', 'give', 'anywhere', 'whence', '’m', 'beyond', 'out', 'via', 'who', 'enough', 'we', 'until', "'m", 'make', 'thence', 'up', "'ll", 'formerly', 'however', 'under', 'show', 'keep', 'were', 'using', 'two', 'once', 'would', 'in', 'everyone', 'against', 'themselves', 'last', 'have', 'wherein', 'whatever', 'everywhere', 'thru', 'former', 'otherwise', 'well', 'anyone', 'some', 'least', 'therefore', 'thereby', 'done', 'whereafter', 'whoever', 'during', 'already', 'not', 'ca', 'none', 'say', 'thereupon', 'no', 'their', 'throughout', 'still', 'nothing', 'twelve', 'if', 'elsewhere', 'does', 'serious', 'these', 'n’t', 'further', "'ve", '’ve', 'somewhere', 'why', 'besides', 'both', 'top', 'i', 'anything', 'upon', 'mostly', 'when', 'just', 'either', 'from', 'being', 'beforehand', 'towards', 'fifteen', 'can', 'seems', 'an', 'really', 'whereupon', '’re', 'toward', 'never', 'is', 'whenever', 'together', 'him', 'any', 'yourselves', 'through', 'quite', 'yourself', 'hereafter', 'nevertheless', 'has', 'then', 'something', 'become', 'though', 'above', 'thereafter', 'seem', 'another', 'hundred', 'became', 'each', 'you', 'be', 'one', 'are', 'various', 'now', 'whole', '’ll', 'everything', 'latterly', 'name', 'nobody', 'that', 'could', 'part', 'and', 'cannot', 'hereby', 'also', 'many', 'noone', 'with', "'d", '’s', 'back', 'was', 'alone', 'down', 'get', 'itself', 'along', 'do', 'all', 'herein', 'across', 'amongst', 'side', 'sometimes', 'nor', 'it', 'three', 'anyhow', 'often', 'front', 'onto', 'us', 'such', 'after', 'while', 'latter', 'regarding', 'into', 'eight', 'yet', 'should', 'myself', 'someone', 'nine', 'put', 'yours', 'hereupon', 'again', 'other', 'beside', 'there', 'every', 'fifty', 'must', 'see', 'except', 'by', 'ours', 'ourselves', 'unless', 'whom', 'his', 'am', 'between', 'six', '‘m', 'bottom', 'four', 'call', 'or', 'those', '‘d', 'perhaps', 'than', 'been', 'among', 'most', 'sometime', 'neither', 'whose', 'somehow', 'much', 'her', 'he', 'rather', 'own', '’d', 'five', 'where', '‘ve', '‘re', 'twenty', 'per', 'off', 'whither', 'for', 'around', 'this', 'below', 'therein', 'always', 'only', 'full', 'herself', 'how', 'them', 'seemed', "n't", 'take', 're', 'without', '‘s', 'even', 'to', 'hers', 'himself', 'first', 'namely', 'whereby', 'becomes', 'your', 'nowhere', 'because', '‘ll', 'behind', 'please', 'so', "'s", 'me', 'doing', 'becoming', 'whether', 'mine', 'on', 'else', 'due', 'they', 'empty', 'will', 'but', 'may', "'re", 'meanwhile', 'our', 'made', 'as', 'afterwards', 'before', 'hence', 'did', 'sixty', 'forty', 'wherever', 'almost', 'my', 'although', 'more', 'whereas', 'seeming']

In [42]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

print(list(ENGLISH_STOP_WORDS))  # About 127 words

['eleven', 'very', 'few', 'several', 'amount', 'a', 'find', 'cant', 'at', 'indeed', 'about', 'anyway', 'since', 'over', 'within', 'interest', 'detail', 'its', 'the', 'she', 'thus', 'ten', 'might', 'sincere', 'what', 'less', 'too', 'go', 'of', 'which', 'had', 'moreover', 'next', 'here', 'others', 'move', 'same', 'un', 'ever', 'third', 'give', 'anywhere', 'whence', 'beyond', 'out', 'via', 'who', 'enough', 'we', 'until', 'thence', 'up', 'formerly', 'however', 'under', 'show', 'ie', 'keep', 'were', 'two', 'once', 'would', 'in', 'everyone', 'against', 'themselves', 'fill', 'last', 'have', 'wherein', 'whatever', 'everywhere', 'thru', 'former', 'otherwise', 'well', 'anyone', 'some', 'least', 'therefore', 'thereby', 'done', 'whereafter', 'whoever', 'during', 'inc', 'already', 'not', 'found', 'none', 'thereupon', 'no', 'their', 'throughout', 'still', 'de', 'nothing', 'twelve', 'if', 'elsewhere', 'these', 'serious', 'bill', 'further', 'somewhere', 'why', 'besides', 'both', 'top', 'i', 'anything', 'upon', 'mostly', 'when', 'either', 'from', 'being', 'beforehand', 'towards', 'fifteen', 'can', 'seems', 'an', 'whereupon', 'toward', 'never', 'is', 'whenever', 'together', 'him', 'any', 'yourselves', 'through', 'yourself', 'hereafter', 'nevertheless', 'has', 'then', 'something', 'become', 'con', 'above', 'though', 'thereafter', 'seem', 'another', 'hundred', 'became', 'amoungst', 'each', 'you', 'be', 'one', 'are', 'now', 'whole', 'everything', 'latterly', 'name', 'nobody', 'that', 'could', 'part', 'and', 'cannot', 'hereby', 'also', 'many', 'noone', 'with', 'back', 'was', 'alone', 'couldnt', 'system', 'down', 'get', 'itself', 'along', 'do', 'all', 'herein', 'across', 'amongst', 'side', 'sometimes', 'nor', 'it', 'three', 'anyhow', 'often', 'front', 'onto', 'us', 'such', 'after', 'while', 'latter', 'into', 'eight', 'etc', 'yet', 'should', 'myself', 'someone', 'nine', 'put', 'yours', 'hereupon', 'again', 'other', 'beside', 'there', 'thin', 'every', 'fifty', 'must', 'see', 'mill', 'except', 'by', 'ours', 'ourselves', 'ltd', 'whom', 'his', 'am', 'between', 'six', 'bottom', 'four', 'call', 'or', 'those', 'perhaps', 'than', 'been', 'among', 'most', 'sometime', 'fire', 'neither', 'whose', 'somehow', 'much', 'her', 'he', 'rather', 'own', 'five', 'where', 'twenty', 'per', 'off', 'thick', 'whither', 'for', 'around', 'this', 'below', 'therein', 'hasnt', 'always', 'only', 'full', 'herself', 'how', 'them', 'seemed', 'take', 're', 'describe', 'without', 'even', 'to', 'hers', 'himself', 'first', 'namely', 'whereby', 'becomes', 'your', 'nowhere', 'because', 'behind', 'please', 'so', 'me', 'becoming', 'whether', 'mine', 'on', 'else', 'due', 'they', 'empty', 'will', 'but', 'may', 'meanwhile', 'eg', 'made', 'our', 'as', 'afterwards', 'before', 'hence', 'sixty', 'forty', 'cry', 'wherever', 'almost', 'my', 'co', 'although', 'more', 'whereas', 'seeming']

In [49]:
#this is how i can combine all the stop words
combined = set(stopwords.words('english')) | STOP_WORDS | ENGLISH_STOP_WORDS
print(sorted(combined))
print (len(combined))
combined_stop_word=list(combined)

["'d", "'ll", "'m", "'re", "'s", "'ve", 'a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'ain', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'aren', "aren't", 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'ca', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldn', "couldn't", 'couldnt', 'cry', 'd', 'de', 'describe', 'detail', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'hasnt', 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", "he's", 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', "i'd", "i'll", "i'm", "i've", 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', 'just', 'keep', 'last', 'latter', 'latterly', 'least', 'less', 'll', 'ltd', 'm', 'ma', 'made', 'make', 'many', 'may', 'me', 'meanwhile', 'might', 'mightn', "mightn't", 'mill', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'mustn', "mustn't", 'my', 'myself', "n't", 'name', 'namely', 'needn', "needn't", 'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'n‘t', 'n’t', 'o', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps', 'please', 'put', 'quite', 'rather', 're', 'really', 'regarding', 's', 'same', 'say', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', "should've", 'shouldn', "shouldn't", 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system', 't', 'take', 'ten', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', "they'd", "they'll", "they're", "they've", 'thick', 'thin', 'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'unless', 'until', 'up', 'upon', 'us', 'used', 'using', 'various', 've', 'very', 'via', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'well', 'were', 'weren', "weren't", 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'won', "won't", 'would', 'wouldn', "wouldn't", 'y', 'yet', 'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves', '‘d', '‘ll', '‘m', '‘re', '‘s', '‘ve', '’d', '’ll', '’m', '’re', '’s', '’ve']
428

In [45]:
# we can also use external set of stop words by reading the file or by giving the list of words
#with open("/Users/subham/Desktop/data/class_360/text mining /txtmining/Datasets NLP/stopwords_en.txt","r") as extra_stopwords:
#    stopwords=sw.read()

with open("/Users/subham/Desktop/data/class_360/text mining /txtmining/Datasets NLP/stopwords_en.txt","r") as sw1:
    stowords = sw1.read()

# to convert it into list we split the data 

stowords=stowords.split()

stowords

['a',
 "a's",
 'able',
 'about',
 'above',
 'according',
 'accordingly',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 "ain't",
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apart',
 'appear',
 'appreciate',
 'appropriate',
 'are',
 "aren't",
 'around',
 'as',
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'available',
 'away',
 'awfully',
 'b',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'both',
 'brief',
 'but',
 'by',
 'c',
 "c'mon",
 "c's",
 'came',
 'can',
 "can't",
 'cannot',
 'cant',
 'cause',
 'causes',
 'certain',
 'certainly',
 'changes',
 'clearly',
 'co',
 'com',
 'come',
 'comes',
 'concerning',
 'consequently',
 'consider',
 'considering',
 'contain',
 'containing',
 'contains',
 'corresponding',
 'could',
 "couldn't",
 'course',
 'currently',
 'd',
 'definitely',
 'described',
 'despite',
 'did',
 "didn't",
 'different',
 'do',
 'does',
 "doesn't",
 'doing',
 "don't",
 'done',
 'down',
 'downwards',
 'during',
 'e',
 'each',
 'edu',
 'eg',
 'eight',
 'either',
 'else',
 'elsewhere',
 'enough',
 'entirely',
 'especially',
 'et',
 'etc',
 'even',
 'ever',
 'every',
 'everybody',
 'everyone',
 'everything',
 'everywhere',
 'ex',
 'exactly',
 'example',
 'except',
 'f',
 'far',
 'few',
 'fifth',
 'first',
 'five',
 'followed',
 'following',
 'follows',
 'for',
 'former',
 'formerly',
 'forth',
 'four',
 'from',
 'further',
 'furthermore',
 'g',
 'get',
 'gets',
 'getting',
 'given',
 'gives',
 'go',
 'goes',
 'going',
 'gone',
 'got',
 'gotten',
 'greetings',
 'h',
 'had',
 "hadn't",
 'happens',
 'hardly',
 'has',
 "hasn't",
 'have',
 "haven't",
 'having',
 'he',
 "he's",
 'hello',
 'help',
 'hence',
 'her',
 'here',
 "here's",
 'hereafter',
 'hereby',
 'herein',
 'hereupon',
 'hers',
 'herself',
 'hi',
 'him',
 'himself',
 'his',
 'hither',
 'hopefully',
 'how',
 'howbeit',
 'however',
 'https',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'ie',
 'if',
 'ignored',
 'immediate',
 'in',
 'inasmuch',
 'inc',
 'indeed',
 'indicate',
 'indicated',
 'indicates',
 'inner',
 'insofar',
 'instead',
 'into',
 'inward',
 'is',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'j',
 'just',
 'k',
 'keep',
 'keeps',
 'kept',
 'know',
 'knows',
 'known',
 'l',
 'last',
 'lately',
 'later',
 'latter',
 'latterly',
 'least',
 'less',
 'lest',
 'let',
 "let's",
 'like',
 'liked',
 'likely',
 'little',
 'look',
 'looking',
 'looks',
 'ltd',
 'm',
 'mainly',
 'many',
 'may',
 'maybe',
 'me',
 'mean',
 'meanwhile',
 'merely',
 'might',
 'more',
 'moreover',
 'most',
 'mostly',
 'much',
 'must',
 'my',
 'myself',
 'n',
 'name',
 'namely',
 'nd',
 'near',
 'nearly',
 'necessary',
 'need',
 'needs',
 'neither',
 'never',
 'nevertheless',
 'new',
 'next',
 'nine',
 'no',
 'nobody',
 'non',
 'none',
 'noone',
 'nor',
 'normally',
 'not',
 'nothing',
 'novel',
 'now',
 'nowhere',
 'o',
 'obviously',
 'of',
 'off',
 'often',
 'oh',
 'ok',
 'okay',
 'old',
 'on',
 'once',
 'one',
 'ones',
 'only',
 'onto',
 'or',
 'other',
 'others',
 'otherwise',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'outside',
 'over',
 'overall',
 'own',
 'p',
 'particular',
 'particularly',
 'per',
 'perhaps',
 'placed',
 'please',
 'plus',
 'possible',
 'presumably',
 'probably',
 'provides',
 'q',
 'que',
 'quite',
 'qv',
 'r',
 'rather',
 'rd',
 're',
 'really',
 'reasonably',
 'regarding',
 'regardless',
 'regards',
 'relatively',
 'respectively',
 'right',
 's',
 'said',
 'same',
 'saw',
 'say',
 'saying',
 'says',
 'second',
 'secondly',
 'see',
 'seeing',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'seen',
 'self',
 'selves',
 'sensible',
 'sent',
 'serious',
 'seriously',
 'seven',
 'several',
 'shall',
 'she',
 'should',
 "shouldn't",
 'since',
 'six',
 'so',
 'some',
 'somebody',
 'somehow',
 'someone',
 'something',
 'sometime',
 'sometimes',
 'somewhat',
 'somewhere',
 'soon',
 'sorry',
 'specified',
 'specify',
 'specifying',
 'still',
 'sub',
 'such',
 'sup',
 'sure',
 't',
 "t's",
 'take',
 'taken',
 'tell',
 'tends',
 'th',
 'than',
 'thank',
 'thanks',
 'thanx',
 'that',
 "that's",
 'thats',
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 "there's",
 'thereafter',
 'thereby',
 'therefore',
 'therein',
 'theres',
 'thereupon',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'think',
 'third',
 'this',
 'thorough',
 'thoroughly',
 'those',
 'though',
 'three',
 'through',
 'throughout',
 'thru',
 'thus',
 'to',
 'together',
 'too',
 'took',
 'toward',
 'towards',
 'tried',
 'tries',
 'truly',
 'try',
 'trying',
 'twice',
 'two',
 'u',
 'un',
 'under',
 'unfortunately',
 'unless',
 'unlikely',
 'until',
 'unto',
 'up',
 'upon',
 'us',
 'use',
 'used',
 'useful',
 'uses',
 'using',
 'usually',
 'uucp',
 'v',
 'value',
 'various',
 'very',
 'via',
 'viz',
 'vs',
 'w',
 'want',
 'wants',
 'was',
 "wasn't",
 'way',
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'welcome',
 'well',
 'went',
 'were',
 "weren't",
 'what',
 "what's",
 'whatever',
 'when',
 'whence',
 'whenever',
 'where',
 "where's",
 'whereafter',
 'whereas',
 'whereby',
 'wherein',
 'whereupon',
 'wherever',
 'whether',
 'which',
 'while',
 'whither',
 'who',
 "who's",
 'whoever',
 'whole',
 'whom',
 'whose',
 'why',
 'will',
 'willing',
 'wish',
 'with',
 'within',
 'without',
 "won't",
 'wonder',
 'would',
 'would',
 "wouldn't",
 'x',
 'y',
 'yes',
 'yet',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'z',
 'zero',
 '...']

In [33]:
# TO ADD MORE STOPWORDS
extra_stop_word=["The","mobile","time","\n","android","phone","device","screen","battery","product","apple","good","day","price","launched","I","easy","browser","...","Apple","Pro ","Max","iphone","pro","iPhone","prO","amazon"]

In [46]:
# We also have punctuations which we can ignore from our set of words just like stopwords.

import string

punct =string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [51]:
all_stop_words=stowords + extra_stop_word + combined_stop_word

len(all_stop_words)

1028

In [52]:


#reading the text file

with open('/Users/subham/Desktop/data/360 assignment /text mining/i_phone13.text','r',encoding='utf-8') as sw:
    iphone_review=sw.read()
    
iphone_review

'[\'\\n\\n  (Update 13.121.2021 will be added soon at the last for unnecessary/money-wasting accessories)Samsung does it first...Apple Does it RIGHT!!So, I switched from Android (Galaxy Note user since 2015, upgrading each year except for Note 7)…The iPhone 13 Pro Max has a design very similar to the iPhone 12 Pro Max — the only discernible change is the thicker camera bump which also has a larger square now. This highlights the one part of the phone that has seen significant change over the past year.On the display side, the notch has now been made smaller. But it has by no means gone away and I did not think this year the display is getting more real estate with this fix. Strangely, I felt the iPhone 13 Pro Max weighed a lot…240 grams!!(Will not run through the spec-sheet. Readily available online)What’s good?Let me get one thing straight. It is pointless talking about most of the features of an iPhone flagship. They are usually what you expect and maybe a tab better than what you anticipated. So, everything from the design, to the actual processing power of this device is top-notch. But that is what you would expect from a top-end Apple device. A top-end device that costs more than a top-end laptop from the same company.So, let’s get to the features that are new.• On the iPhone 13 Pro Max, Apple is literally flexing its camera muscles. The big bump on the back is this very muscle on show. The lenses too are larger and deeper than before, a clear indication that this camera takes in more light and this performs better in low light.• All this translates to much better photos when compared to the last generation Pro Max phones. There is much better detail, greater clarity in low light, and overall a better character with whatever you click.• But that’s not even what Apple wants to sell this time. For that Apple has lined up its first macro mode. Macro mode is in no way a new feature in smartphones. But the way Apple is doing it is certainly novel. There is no Macro mode as such in the camera app. But as you take the camera really close to a subject the phone switches to the ultra-wide lens and switches on macro.• The results are really good and possibly the best close-up shots on any smartphone. But that is if the light is good. Also, I noticed that the images are not sharp all through and there is a focal point where it’s perfect, that seems to be because it’s being shot on the ultra-wide lens• These days we don’t use the phone much on a smartphone. We buy our smartphones for a plethora of uses in which the original use, that of making a voice call to someone, has been relegated to the sidelines. In fact, smartphones these days are so smart and powerful that many buy these devices primarily for other uses, often not even bothering to add a SIM card after the purchase. There are those who use the smartphone to the best of its ability, trying to push it to the limits as it keeps adding to their convenience and eases workflows. The Apple iPhone 13 Pro Max is aimed at this last set of users.• The camera magic goes up one notch when you switch to video. Apple has unleashed its processing power in tandem with the three lenses and its computational photography algorithms to offer Cinematic Mode. This mode, like in the thousands of movie scenes it’s trained on, is able to shift focus from one subject to the other when the attention or gaze of the subject shifts. Doing it on movie cameras is tough enough and Apple is doing it automatically. And that’s not all, you can change this whole editing video in the post process. All over, mind-boggling stuff.There is one more weapon that Apple hasn’t taken out of its quiver yet and that is ProRes, almost a RAW format for video.What the new camera capabilities do is that they make the iPhone a viable replacement for a lot of professional video cameras out there. So, if you are a creator then this is maybe the best videos camera you can buy now. Yes, there are better cameras out there, but none can edit what it captures. And also upload it to the Internet soon after it’s done with output. That’s where the Pro in this iPhone starts making sense.It’s not just branding, it’s a calling card.• There will be another set of users who will like the other Pro inside this phone. Yes, gamers will love the ProMotion adaptive refresh rate. Again, nothing really new, but then Apple does even old things differently. The iPhone 13 Pro Max will switch from 10Hz refresh rate to 120Hz as the content demands. And, no, that’s not for the user to decide. She can leave that complex decision-making to the A15 Bionic that powers this phone.• Frankly, doing regular stuff you can’t even figure out that there is something happening with this display. That’s how smooth this is. But when you start playing some games like Thumper: Pocket Edition+ you do see a difference in how this phone renders the game compared to earlier generations. Remember, this phone has one extra graphics core which is now solely for use on videos.• So how powerful is this phone? Well, powerful enough to edit 4K videos and change their focus. All this should have made the iPhone 13 Pro Max a power guzzler. The beauty of the phone is that despite all this the phone offers better battery life than any iPhone before this.In fact, during the review period, I have used the phone for over 36 hours, charging the phone only upto 100 once with 10% still left!! Crazy!What’s not that good?• The "Apple Tax"!! That\\\'s what I call the unscrupulous money demanded by Apple.• The iPhone 13 Pro Max is a superb phone, but it pulls back on some punches if you were expecting some features that would blow your mind and change your life on a daily basis. The Cinematic Mode is a testament to how powerful and smartphones are now, but it’s not a feature that’s very useful to regular people. Of course, wedding photographers and creators will be thrilled, but not the top executive who’s upgrading to his next phone.• In that sense, the improved battery life is the feature that really impacts the most number of people. The iPhone clearly seems to have come to a point where the next big change will have to be a disruptor and not something incremental. And that it is still running 20W charger.Should you buy?The iPhone 13 Pro Max is clearly the best phone out there. But should everyone buy this phone? No. That’s not because the Pro Max has any issues, but because the iPhone 13 itself is so good when it comes to regular users. The Pro is clearly aimed the those who will find use for the better camera, display, and graphics power. If you are a creator, or a developer working on cutting-edge apps, then this phone is a must-have for you. Regular people will of course buy this phone too, but to show the world they are ahead of the race like the phone they own.And the pro max or any other line-up will punch a hole in your pocket deep enough to reach out to your kidney. That won’t hurt if you are “filthy-rich” though.Didn’t spam the gallery with “unboxing”, “swiveling”, “showing-off” the phone…as other users are already on it!*********************************************************************************************************************Accessories:However, I’m attaching an image with all the accessories that I bundled with this phone (two left out as they are in transit). Also linking them here for you to check out:• USB 3.0 OTG Adapter Cable:https://www.amazon.in/gp/product/B097JQN64T/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Spigen Smart Fold Magnetic Wallet Card Holder Designed for MagSafe with Kickstand:https://www.amazon.in/gp/product/B08S1XM54D/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• USB-C to Lightning Cable, (20 cm, MFi-Certified), PD Fast Charging Cable:https://www.amazon.in/gp/product/B07WVXGFCJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• 0.5 Feet Short Lightning to USB Data Sync Cable [MFi Certified]:https://www.amazon.in/gp/product/B01FCUJCLA/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1• Magnetic Compatible Case Back Cover Magnetic Wireless Charging Anti-Fingerprint Shockproof Bumper:https://www.amazon.in/gp/product/B09CRVQCH5/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Denim Flip Cover Premium Luxury Slim Wallet Folio Case Magnetic Cover:https://www.amazon.in/gp/product/B094FHN47Q/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Privacy Tempered Glass Screen Protector:https://www.amazon.in/gp/product/B09GBP2NXX/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1(the above are in one image)*********************************************************************************************************************Bought later:• Magnetic Wireless Charging Conversion Kit:https://www.amazon.in/gp/product/B08S6XQFDM/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1• Mag-Safe Magnetic Phone Holder Leather Pad:https://www.amazon.in/gp/product/B08RDX7GZ5/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1(Creating a collage with all these stuffs for reference)*********************************************************************************************************************11.11.2021:Also added these to my arsenal:• Metal Bumper:https://www.amazon.in/gp/product/B09FZKKPLM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Magsafe holder for Laptop:https://www.amazon.in/gp/product/B095YY319F/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• USB C to USB A:https://www.amazon.in/gp/product/B0963ZXFHJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Camera Module Guard:https://www.amazon.in/gp/product/B09H36MHF6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1• Charging Station:https://www.amazon.in/gp/product/B096FNG2MJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1  ***  ***  ***  ***That\\\'s all folks!\\n\\n\', \'\\n\\n  Need camera software update rest of that everything is fine.\\n\\n\', \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0Best phone 💙 blue colour is awesome .. BEAST 💙🍎\\n\\n\', "\\n\\n  According to me guysFirst of all I haven\'t purchased iPhoneSecondly according to me if you have this much budget of more than 1lakhs spending on mobile is not worth at allInfact you can invest that money on apple stock or other  stock  so that the money could get doubled in future bcoz buying  iPhone is a depreciating assetHope you understand 🙂\\n\\n", \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0The phone is excellent. this is my first iPhone. I was considering Samsung galaxy s 21 ultra because of its macro photography. After iPhone launched this new one and announced macro photography ability of the phone I decided to go for this one blindfoldedly. The delivery was delayed because of demand supply difference but it was worth the wait. The first thing I did it was put on the the glass shield and cover. I thought it would kill the looks but it still looks nice. The iOS is very easy to use. Simple to go to all the settings.\\n\\n\', "\\n\\n  I previously owned the 12 Pro Max and shifted to the 13 and boy I am not disappointed. What I loved most is the camera(pic attached of night photography The pic I uploaded was shot at 7 pm. Apart from the camera, what I liked is the refresh rate when scrolling through supported apps giving me less lag input. Overall I\'d choose the iPhone any day over all other smartphone because it\'s super good and has value for the money that I spent on and the only down side being the cost of it.\\n\\n", \'\\n\\n  With all the incremental improvements in the areas which really matter - camera, battery and display - this is a beast of an iPhone.\\n\\n\', \'\\n\\n  Well I switched from One plus to iphone. Now the fact is this was a dream for me to but a iphone. So bought it. Everything is marvellous.. there are various technical reviews so I am not going to write about it again… Comparing ios with android never made any sense to me because two are completely different platform and for different purpose. Various people gave reviews comparing with android phone which is not practical…  understand your need and if you have the money the just go for it.. you wont regret\\n\\n\', \'\\n\\n  This is the best iPhone so far, earlier i used to think iPhones doesn’t have the best battery backup but with this iPhone 13 pro max , it completely changed my view!!!I feel this is the best iPhone mobile so far from apple in all the aspects.\\n\\n\', \'\\n\\n  It elevates the already great Iphone experience with a much better (pro motion) display and excellent camera!\\n\\n\', "\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0I switched from 11 pro max to 13 pro max. As for the phone, it is the best iPhone experience you can have, simple. Yes it is expensive, but if you have your sight set for it, it is the best phone you can buy.Pros:> Display is gorgeous! 120Hz is a must have in a Premium device and this one delivers it.> Battery life in unbelievable, not able to drain it in a single day, always ending up with 30~35% battery at the end of the day!> Build quality is unquestionably Apple, Solid and Beautiful.> New camera setup is better than most other phones, andunquestionably it has the best Video recording as usual. Finally 3x zoom makes it better in zoom scenes than the past iPhones> Flat screen helps in applying screen protector and using the device in general.> Performance is better than any other Smartphone out there, and never found any lag or hiccup in even gameplay time.Cons:> Price! Yes it is extremely expensive in India but when other Flagships from Samsung have also touched these prices, it is not a factor to think about.> Heaviest phone I\'ve ever used! 240 grams is a lot if weight, although it means the build is solid and battery is huge too.> Unconventional dual sim style (Physical SIM + eSIM) can be an issue for some users who need to use 2 physical SIM cards.> Usual limitations of iOS (lime lack of customisation) that Android users love to point out, even though the limitations are never really deal breakers.\\n\\n", "\\n\\n  I was very skeptical about the genuineness of the product that I would receive as it was not available in stock in stores. So, I brought all my gut feeling together and made this purchase. The product was delivered in time. When I opened the box, it was strikingly beautiful. I checked for its authenticity by verifying it from all different ways. Now, most importantly a genuine Apple iPhone 13 pro max phone was in my hand. It works great for me and has a longer battery life than the previous phones that I\'ve had.\\n\\n", \'\\n\\n  Great Product. Worth buying! Amazon Delivery is also Great!\\n\\n\', \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0From iPhone 6S in 2015 to iPhone 13 pro max in 2021 ,, one thing that still remains the same is it’s performance! I own an oneplus device but there is no comparison between these two! Apple made it a beast. From camera to gaming.. everything is top notch. The battery life is superb, best till now. Normal usage can go upto 3 days with full charge. Bought the earpods pro & iwatch to compliment this beast🤭\\n\\n\', \'\\n\\n  This phone is superbly amazing. The features the display, everything is so smooth. Camera is damn good.\\n\\n\', \'\\n\\n  Shifting from iPhone 8 (64 GB) to iPhone 13 Pro Max (1 TB). I am able to use my new phone the whole day and still enough battery is left. Really impressed by the build quality and durability. The phone weighs slightly heavier than the iPhone 12 Pro Max model that my sister uses. Really satisfied with the Camera, Display, Screen brightness and Sound quality as well.\\n\\n\', \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\', "\\n\\n  Major points to consider :Massive battery life, I usually charge my phone by morning 5:30 to 7 and it\'s got full charged and I use it till over night and charge it back next day with 30% battery left, so I like it,Best screen.Best Camera.It\'s fastThat\'s all I care, so it\'s good for me.Cons- Expensive.\\n\\n", \'\\n\\n  1. Blue Colour is good.2. Battery is very long lasting. For my usage with 1 full charge I can use it for 2 full days.3. Camera should be improved. There are competitor phones for way lesser price than this phone with very good camera quality.4. Phone is little heavy but will get used to after some days.5. Sound quality is amazing.6. Display is also very good. But can’t feel much difference with 120 Hz display and older iPhones.7. Overall performance of the phone is good.\\n\\n\', \'\\n\\n  Trusted seller and I got it 1 week back just unboxed yesterday Well Packed like a cover u can keep it in ur pocket,It’s the best Human Made Mobile in the world why it’s because most costlier than ever in mobile industryI switched from Samsung to Apple it’s too hard to transfer WhatsApp I spent more but it’s too tricky so no time I leaved itOthercamera 5/5 may be I don’t know it will be competitive fr DSLR and mirrorless not above price rangeCall quality and display,sound, 5/5 as a android user to appleOverall I hope I will use fr few yearsJai Hind\\n\\n\', \'\\n\\n  Well apple products always live up to expectations despite of the price factor, to share my views on the mobile - amazing camera ,great call quality and feels very premium ,wonderful battery life, lastly can multitask with out any performance glitch..\\n\\n\', \'\\n\\n  iOS 15 feels silky smooth with 120Hz refresh rate. And A15 has no competition.\\n\\n\', \'\\n\\n  Writing after one week of usage. I switched from Samsung A50 (light and good quality. was very happy)All good and enough reviews are there online. Pro max is bulky. Hand will pain after holding for 10 mins for a call or browsing. Though many reviews told that, I overlooked the aspect.Think of it before buying. It is not a small thing. You won’t appreciate all others aspects of mobile when your hand starts paining.\\n\\n\', \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0Battery quality is very good and average use it stands 2-3 days and the set is value for money\\n\\n\', \'\\n\\n  So it is at the top of the food chain. Worth the money.\\n\\n\', \'\\n\\n  Overall phone is excellent. Specially camera and screen.\\n\\n\', \'\\n\\n  One of the best mobile Phone! The picture quality, the speed, usability, displays everything is super awesome of the mobile.\\n\\n\', \'\\n\\n  Top notch in every aspect\\n\\n\', \'\\n\\n\\n\\n\\n                    The media could not be loaded.\\n                \\n\\n\\n\\n\\n  \\xa0Just excellent 🙈\\n\\n\', \'\\n\\n  so far best phone for me, had, and still having great experience using it and will have in future i am sure.\\n\\n\', \'\\n\\n  Do The Price Is High But Product Is True For Money .\\n\\n\', \'\\n\\n  It’s a magical device.\\n\\n\', \'\', \'\\n\\n  Typical apple product. Very expensive but feels very premium in all respects..\\n\\n\', \'\\n\\n  Amazing build quality, camera, battery, display and surround sound\\n\\n\', \'\\n\\n  Single word … Amazing !\\n\\n\', \'\\n\\n  Buy from store\\n\\n\', \'\\n\\n  I love serria colour\\n\\n\', \'\\n\\n  Value is for productUse it feel it 😇😇😇\\n\\n\', \'\\n\\n  Very good\\n\\n\', \'\\n\\n  Nice product\\n\\n\', \'\\n\\n  price is good then 12 pro maxx massive powerfull iPhone 13 pro maxx\\n\\n\', \'\\n\\n  Excellent\\n\\n\', \'\\n\\n  Damm good\\n\\n\', \'\', \'\\n\\n  Totally worth\\n\\n\', \'\\n\\n  5starAwesome\\n\\n\', \'\\n\\n  This is not really worth 1.3 lakhs ! Nothing is so great which asks for this price !! Same old notch, outdated design , no charger , even all these charger ,phone cover and screen guard costs another 5k ! Only buy if you really need it and it was your dream to have , people giving here 5 stars are those who dreamt of having Apple bra

In [82]:
# How to impliment punkt
import nltk
import string
from nltk.corpus import stopwords

all_stop_words=stowords + extra_stop_word + combined_stop_word
punct =string.punctuation

#data = "India (Hindi: Bhārat), officially the Republic of India, is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west; China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand and Indonesia."
clean_data =[]

words=nltk.word_tokenize(iphone_review)
for w in words:
    if w not in punct:
        if w not in all_stop_words:
            clean_data.append(w)
                        
clean_data

["'\\n\\n",
 'Update',
 '13.121.2021',
 'added',
 'unnecessary/money-wasting',
 'accessories',
 'Samsung',
 'Does',
 'RIGHT',
 'So',
 'switched',
 'Android',
 'Galaxy',
 'Note',
 'user',
 '2015',
 'upgrading',
 'year',
 'Note',
 '7',
 '…The',
 '13',
 'Pro',
 'design',
 'similar',
 '12',
 'Pro',
 '—',
 'discernible',
 'change',
 'thicker',
 'camera',
 'bump',
 'larger',
 'square',
 'This',
 'highlights',
 'significant',
 'change',
 'past',
 'year.On',
 'display',
 'notch',
 'smaller',
 'But',
 'means',
 'year',
 'display',
 'real',
 'estate',
 'fix',
 'Strangely',
 'felt',
 '13',
 'Pro',
 'weighed',
 'lot…240',
 'grams',
 'Will',
 'run',
 'spec-sheet',
 'Readily',
 'online',
 'What',
 '’',
 'Let',
 'thing',
 'straight',
 'It',
 'pointless',
 'talking',
 'features',
 'flagship',
 'They',
 'expect',
 'tab',
 'anticipated',
 'So',
 'design',
 'actual',
 'processing',
 'power',
 'top-notch',
 'But',
 'expect',
 'top-end',
 'A',
 'top-end',
 'costs',
 'top-end',
 'laptop',
 'company.So',
 '’',
 'features',
 'new.•',
 'On',
 '13',
 'Pro',
 'literally',
 'flexing',
 'camera',
 'muscles',
 'big',
 'bump',
 'muscle',
 'lenses',
 'larger',
 'deeper',
 'clear',
 'indication',
 'camera',
 'takes',
 'light',
 'performs',
 'low',
 'light.•',
 'All',
 'translates',
 'photos',
 'compared',
 'generation',
 'Pro',
 'phones',
 'There',
 'greater',
 'clarity',
 'low',
 'light',
 'character',
 'click.•',
 'But',
 '’',
 'sell',
 'For',
 'lined',
 'macro',
 'mode',
 'Macro',
 'mode',
 'feature',
 'smartphones',
 'But',
 'There',
 'Macro',
 'mode',
 'camera',
 'app',
 'But',
 'camera',
 'close',
 'subject',
 'switches',
 'ultra-wide',
 'lens',
 'switches',
 'macro.•',
 'results',
 'possibly',
 'close-up',
 'shots',
 'smartphone',
 'But',
 'light',
 'Also',
 'noticed',
 'images',
 'sharp',
 'focal',
 'point',
 '’',
 'perfect',
 '’',
 'shot',
 'ultra-wide',
 'lens•',
 'These',
 'days',
 '’',
 'smartphone',
 'We',
 'buy',
 'smartphones',
 'plethora',
 'original',
 'making',
 'voice',
 'relegated',
 'sidelines',
 'In',
 'fact',
 'smartphones',
 'days',
 'smart',
 'powerful',
 'buy',
 'devices',
 'primarily',
 'bothering',
 'add',
 'SIM',
 'card',
 'purchase',
 'There',
 'smartphone',
 'ability',
 'push',
 'limits',
 'adding',
 'convenience',
 'eases',
 'workflows',
 '13',
 'Pro',
 'aimed',
 'set',
 'users.•',
 'camera',
 'magic',
 'notch',
 'switch',
 'video',
 'unleashed',
 'processing',
 'power',
 'tandem',
 'lenses',
 'computational',
 'photography',
 'algorithms',
 'offer',
 'Cinematic',
 'Mode',
 'This',
 'mode',
 'thousands',
 'movie',
 'scenes',
 '’',
 'trained',
 'shift',
 'focus',
 'subject',
 'attention',
 'gaze',
 'subject',
 'shifts',
 'Doing',
 'movie',
 'cameras',
 'tough',
 'automatically',
 'And',
 '’',
 'change',
 'editing',
 'video',
 'post',
 'process',
 'All',
 'mind-boggling',
 'stuff.There',
 'weapon',
 '’',
 'quiver',
 'ProRes',
 'RAW',
 'format',
 'video.What',
 'camera',
 'capabilities',
 'viable',
 'replacement',
 'lot',
 'professional',
 'video',
 'cameras',
 'So',
 'creator',
 'videos',
 'camera',
 'buy',
 'Yes',
 'cameras',
 'edit',
 'captures',
 'And',
 'upload',
 'Internet',
 '’',
 'output',
 'That',
 '’',
 'Pro',
 'starts',
 'making',
 'sense.It',
 '’',
 'branding',
 '’',
 'calling',
 'card.•',
 'There',
 'set',
 'users',
 'Pro',
 'inside',
 'Yes',
 'gamers',
 'love',
 'ProMotion',
 'adaptive',
 'refresh',
 'rate',
 'Again',
 'things',
 'differently',
 '13',
 'Pro',
 'switch',
 '10Hz',
 'refresh',
 'rate',
 '120Hz',
 'content',
 'demands',
 'And',
 '’',
 'user',
 'decide',
 'She',
 'leave',
 'complex',
 'decision-making',
 'A15',
 'Bionic',
 'powers',
 'phone.•',
 'Frankly',
 'regular',
 'stuff',
 '’',
 'figure',
 'happening',
 'display',
 'That',
 '’',
 'smooth',
 'But',
 'start',
 'playing',
 'games',
 'Thumper',
 'Pocket',
 'Edition+',
 'difference',
 'renders',
 'game',
 'compared',
 'earlier',
 'generations',
 'Remember',
 'extra',
 'graphics',
 'core',
 'solely',
 'videos.•',
 'So',
 'powerful',
 'Well',
 'powerful',
 'edit',
 '4K',
 'videos',
 'change',
 'focus',
 'All',
 '13',
 'Pro',
 'power',
 'guzzler',
 'beauty',
 'offers',
 'life',
 'this.In',
 'fact',
 'review',
 'period',
 '36',
 'hours',
 'charging',
 'upto',
 '100',
 '10',
 'left',
 'Crazy',
 'What',
 '’',
 '•',
 '``',
 'Tax',
 "''",
 'That\\',
 'unscrupulous',
 'money',
 'demanded',
 'Apple.•',
 '13',
 'Pro',
 'superb',
 'pulls',
 'punches',
 'expecting',
 'features',
 'blow',
 'mind',
 'change',
 'life',
 'daily',
 'basis',
 'Cinematic',
 'Mode',
 'testament',
 'powerful',
 'smartphones',
 '’',
 'feature',
 '’',
 'regular',
 'people',
 'Of',
 'wedding',
 'photographers',
 'creators',
 'thrilled',
 'executive',
 '’',
 'upgrading',
 'phone.•',
 'In',
 'sense',
 'improved',
 'life',
 'feature',
 'impacts',
 'number',
 'people',
 'point',
 'big',
 'change',
 'disruptor',
 'incremental',
 'And',
 'running',
 '20W',
 'charger.Should',
 'buy',
 '13',
 'Pro',
 'But',
 'buy',
 'No',
 'That',
 '’',
 'Pro',
 'issues',
 '13',
 'regular',
 'users',
 'Pro',
 'aimed',
 'camera',
 'display',
 'graphics',
 'power',
 'If',
 'creator',
 'developer',
 'working',
 'cutting-edge',
 'apps',
 'must-have',
 'Regular',
 'people',
 'buy',
 'world',
 'ahead',
 'race',
 'own.And',
 'max',
 'line-up',
 'punch',
 'hole',
 'pocket',
 'deep',
 'reach',
 'kidney',
 'That',
 '’',
 'hurt',
 '“',
 'filthy-rich',
 '”',
 'though.Didn',
 '’',
 'spam',
 'gallery',
 '“',
 'unboxing',
 '”',
 '“',
 'swiveling',
 '”',
 '“',
 'showing-off',
 '”',
 'phone…as',
 'users',
 'Accessories',
 'However',
 '’',
 'attaching',
 'image',
 'accessories',
 'bundled',
 'left',
 'transit',
 'Also',
 'linking',
 'check',
 '•',
 'USB',
 '3.0',
 'OTG',
 'Adapter',
 'Cable',
 '//www.amazon.in/gp/product/B097JQN64T/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Spigen',
 'Smart',
 'Fold',
 'Magnetic',
 'Wallet',
 'Card',
 'Holder',
 'Designed',
 'MagSafe',
 'Kickstand',
 '//www.amazon.in/gp/product/B08S1XM54D/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'USB-C',
 'Lightning',
 'Cable',
 '20',
 'cm',
 'MFi-Certified',
 'PD',
 'Fast',
 'Charging',
 'Cable',
 '//www.amazon.in/gp/product/B07WVXGFCJ/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 '0.5',
 'Feet',
 'Short',
 'Lightning',
 'USB',
 'Data',
 'Sync',
 'Cable',
 'MFi',
 'Certified',
 '//www.amazon.in/gp/product/B01FCUJCLA/ref=ppx_od_dt_b_asin_title_s00',
 'ie=UTF8',
 'psc=1•',
 'Magnetic',
 'Compatible',
 'Case',
 'Back',
 'Cover',
 'Magnetic',
 'Wireless',
 'Charging',
 'Anti-Fingerprint',
 'Shockproof',
 'Bumper',
 '//www.amazon.in/gp/product/B09CRVQCH5/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Denim',
 'Flip',
 'Cover',
 'Premium',
 'Luxury',
 'Slim',
 'Wallet',
 'Folio',
 'Case',
 'Magnetic',
 'Cover',
 '//www.amazon.in/gp/product/B094FHN47Q/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Privacy',
 'Tempered',
 'Glass',
 'Screen',
 'Protector',
 '//www.amazon.in/gp/product/B09GBP2NXX/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1',
 'image',
 'Bought',
 '•',
 'Magnetic',
 'Wireless',
 'Charging',
 'Conversion',
 'Kit',
 '//www.amazon.in/gp/product/B08S6XQFDM/ref=ppx_yo_dt_b_asin_title_o00_s00',
 'ie=UTF8',
 'psc=1•',
 'Mag-Safe',
 'Magnetic',
 'Phone',
 'Holder',
 'Leather',
 'Pad',
 '//www.amazon.in/gp/product/B08RDX7GZ5/ref=ppx_yo_dt_b_asin_title_o00_s00',
 'ie=UTF8',
 'psc=1',
 'Creating',
 'collage',
 'stuffs',
 'reference',
 '11.11.2021',
 'Also',
 'added',
 'arsenal',
 '•',
 'Metal',
 'Bumper',
 '//www.amazon.in/gp/product/B09FZKKPLM/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Magsafe',
 'holder',
 'Laptop',
 '//www.amazon.in/gp/product/B095YY319F/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'USB',
 'C',
 'USB',
 'A',
 '//www.amazon.in/gp/product/B0963ZXFHJ/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Camera',
 'Module',
 'Guard',
 '//www.amazon.in/gp/product/B09H36MHF6/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1•',
 'Charging',
 'Station',
 '//www.amazon.in/gp/product/B096FNG2MJ/ref=ppx_yo_dt_b_search_asin_title',
 'ie=UTF8',
 'psc=1',
 'That\\',
 'folks',
 '\\n\\n',
 "'\\n\\n",
 'Need',
 'camera',
 'software',
 'update',
 'rest',
 'fine.\\n\\n',
 "'\\n\\n\\n\\n\\n",
 'media',
 'loaded.\\n',
 '\\n\\n\\n\\n\\n',
 '\\xa0Best',
 '💙',
 'blue',
 'colour',
 'awesome',
 '..',
 'BEAST',
 '💙🍎\\n\\n',
 '``',
 '\\n\\n',
 'According',
 'guysFirst',
 'purchased',
 'iPhoneSecondly',
 'budget',
 '1lakhs',
 'spending',
 'worth',
 'allInfact',
 'invest',
 'money',
 'stock',
 'stock',
 'money',
 'doubled',
 'future',
 'bcoz',
 'buying',
 'depreciating',
 'assetHope',
 'understand',
 '🙂\\n\\n',
 "''",
 "'\\n\\n\\n\\n\\n",
 'media',
 'loaded.\\n',
 '\\n\\n\\n\\n\\n',
 '\\xa0The',
 'excellent',
 'Samsung',
 'galaxy',
 '21',
 'ultra',
 'macro',
 'photography',
 'After',
 'announced',
 'macro',
 'photography',
 'ability',
 'decided',
 'blindfoldedly',
 'delivery',
 'delayed',
 'demand',
 'supply',
 'difference',
 'worth',
 'wait',
 'thing',
 'glass',
 'shield',
 'cover',
 'thought',
 'kill',
 'nice',
 'iOS',
 'Simple',
 'settings.\\n\\n',
 '``',
 '\\n\\n',
 'previously',
 'owned',
 '12',
 'Pro',
 'shifted',
 '13',
 'boy',
 'disappointed',
 'What',
 'loved',
 'camera',
 'pic',
 'attached',
 'night',
 'photography',
 'pic',
 'uploaded',
 'shot',
 '7',
 'pm',
 'Apart',
 'camera',
 'refresh',
 'rate',
 'scrolling',
 'supported',
 'apps',
 'giving',
 'lag',
 'input',
 'Overall',
 'choose',
 'smartphone',
 'super',
 'money',
 'spent',
 'cost',
 'it.\\n\\n',
 "''",
 "'\\n\\n",
 'With',
 'incremental',
 'improvements',
 'areas',
 'matter',
 'camera',
 'display',
 'beast',
 'iPhone.\\n\\n',
 "'\\n\\n",
 'Well',
 'switched',
 'One',
 'Now',
 'fact',
 'dream',
 'So',
 'bought',
 'Everything',
 'marvellous',
 '..',
 'technical',
 'reviews',
 'write',
 'again…',
 'Comparing',
 'ios',
 'sense',
 'completely',
 'platform',
 'purpose',
 'Various',
 'people',
 'gave',
 'reviews',
 'comparing',
 'practical…',
 'understand',
 'money',
 '..',
 'wont',
 'regret\\n\\n',
 "'\\n\\n",
 'This',
 'earlier',
 'iPhones',
 '’',
 'backup',
 '13',
 'max',
 'completely',
 'changed',
 'view',
 'feel',
 'aspects.\\n\\n',
 "'\\n\\n",
 'It',
 'elevates',
 'great',
 'Iphone',
 'experience',
 'motion',
 'display',
 'excellent',
 'camera',
 '\\n\\n',
 '``',
 '\\n\\n\\n\\n\\n',
 'media',
 'loaded.\\n',
 '\\n\\n\\n\\n\\n',
 '\\xa0I',
 'switched',
 '11',
 'max',
 '13',
 'max',
 'As',
 'experience',
 'simple',
 'Yes',
 'expensive',
 'sight',
 'set',
 'buy.Pros',
 'Display',
 'gorgeous',
 '120Hz',
 'Premium',
 'delivers',
 'it.',
 'Battery',
 'life',
 'unbelievable',
 'drain',
 'single',
 'ending',
 '30~35',
 'end',
 'Build',
 'quality',
 'unquestionably',
 'Solid',
 'Beautiful.',
 'New',
 'camera',
 'setup',
 'phones',
 'andunquestionably',
 'Video',
 'recording',
 'usual',
 'Finally',
 '3x',
 'zoom',
 'makes',
 'zoom',
 'scenes',
 'past',
 'iPhones',
 'Flat',
 'helps',
 'applying',
 'protector',
 'general.',
 'Performance',
 'Smartphone',
 'lag',
 'hiccup',
 'gameplay',
 'time.Cons',
 'Price',
 'Yes',
 'extremely',
 'expensive',
 'India',
 'Flagships',
 'Samsung',
 'touched',
 'prices',
 'factor',
 'about.',
 'Heaviest',
 '240',
 'grams',
 'lot',
 'weight',
 'means',
 'build',
 'solid',
 'huge',
 'too.',
 'Unconventional',
 'dual',
 'sim',
 'style',
 'Physical',
 'SIM',
 'eSIM',
 'issue',
 'users',
 '2',
 'physical',
 'SIM',
 'cards.',
 'Usual',
 'limitations',
 'iOS',
 'lime',
 'lack',
 'customisation',
 'Android',
 'users',
 'love',
 'point',
 'limitations',
 'deal',
 'breakers.\\n\\n',
 "''",
 '``',
 '\\n\\n',
 'skeptical',
 'genuineness',
 'receive',
 'stock',
 'stores',
 'So',
 'brought',
 'gut',
 'feeling',
 'purchase',
 'delivered',
 'When',
 'opened',
 'box',
 'strikingly',
 'beautiful',
 'checked',
 'authenticity',
 'verifying',
 'ways',
 'Now',
 'importantly',
 'genuine',
 ...]

In [83]:
# here we have cleaned data now i have to do pos tagging

pos_tagged=nltk.pos_tag(clean_data)
pos_tagged

[("'\\n\\n", 'POS'),
 ('Update', 'NNP'),
 ('13.121.2021', 'CD'),
 ('added', 'VBD'),
 ('unnecessary/money-wasting', 'JJ'),
 ('accessories', 'NNS'),
 ('Samsung', 'NNP'),
 ('Does', 'NNP'),
 ('RIGHT', 'NNP'),
 ('So', 'NNP'),
 ('switched', 'VBD'),
 ('Android', 'NNP'),
 ('Galaxy', 'NNP'),
 ('Note', 'NNP'),
 ('user', 'NN'),
 ('2015', 'CD'),
 ('upgrading', 'JJ'),
 ('year', 'NN'),
 ('Note', 'NN'),
 ('7', 'CD'),
 ('…The', 'NN'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('design', 'NN'),
 ('similar', 'JJ'),
 ('12', 'CD'),
 ('Pro', 'NNP'),
 ('—', 'FW'),
 ('discernible', 'JJ'),
 ('change', 'NN'),
 ('thicker', 'NN'),
 ('camera', 'NN'),
 ('bump', 'NN'),
 ('larger', 'JJR'),
 ('square', 'NN'),
 ('This', 'DT'),
 ('highlights', 'NNS'),
 ('significant', 'JJ'),
 ('change', 'NN'),
 ('past', 'IN'),
 ('year.On', 'NN'),
 ('display', 'NN'),
 ('notch', 'VBP'),
 ('smaller', 'JJR'),
 ('But', 'CC'),
 ('means', 'VBZ'),
 ('year', 'NN'),
 ('display', 'NN'),
 ('real', 'JJ'),
 ('estate', 'NN'),
 ('fix', 'NN'),
 ('Strangely', 'NNP'),
 ('felt', 'VBD'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('weighed', 'VBD'),
 ('lot…240', 'JJ'),
 ('grams', 'NNS'),
 ('Will', 'MD'),
 ('run', 'VB'),
 ('spec-sheet', 'JJ'),
 ('Readily', 'NNP'),
 ('online', 'VB'),
 ('What', 'WP'),
 ('’', 'NNP'),
 ('Let', 'NNP'),
 ('thing', 'NN'),
 ('straight', 'VBD'),
 ('It', 'PRP'),
 ('pointless', 'NN'),
 ('talking', 'VBG'),
 ('features', 'NNS'),
 ('flagship', 'VBP'),
 ('They', 'PRP'),
 ('expect', 'VBP'),
 ('tab', 'NN'),
 ('anticipated', 'VBN'),
 ('So', 'RB'),
 ('design', 'JJ'),
 ('actual', 'JJ'),
 ('processing', 'NN'),
 ('power', 'NN'),
 ('top-notch', 'NN'),
 ('But', 'CC'),
 ('expect', 'VBP'),
 ('top-end', 'VBP'),
 ('A', 'DT'),
 ('top-end', 'JJ'),
 ('costs', 'NNS'),
 ('top-end', 'JJ'),
 ('laptop', 'JJ'),
 ('company.So', 'NN'),
 ('’', 'NN'),
 ('features', 'VBZ'),
 ('new.•', 'VBP'),
 ('On', 'IN'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('literally', 'RB'),
 ('flexing', 'VBG'),
 ('camera', 'NN'),
 ('muscles', 'NNS'),
 ('big', 'JJ'),
 ('bump', 'NN'),
 ('muscle', 'NN'),
 ('lenses', 'VBZ'),
 ('larger', 'JJR'),
 ('deeper', 'JJR'),
 ('clear', 'JJ'),
 ('indication', 'NN'),
 ('camera', 'NN'),
 ('takes', 'VBZ'),
 ('light', 'JJ'),
 ('performs', 'NNS'),
 ('low', 'JJ'),
 ('light.•', 'VBP'),
 ('All', 'DT'),
 ('translates', 'NNS'),
 ('photos', 'NNS'),
 ('compared', 'VBN'),
 ('generation', 'NN'),
 ('Pro', 'NNP'),
 ('phones', 'NNS'),
 ('There', 'EX'),
 ('greater', 'JJR'),
 ('clarity', 'NN'),
 ('low', 'JJ'),
 ('light', 'JJ'),
 ('character', 'NN'),
 ('click.•', 'NN'),
 ('But', 'CC'),
 ('’', 'NNP'),
 ('sell', 'VBP'),
 ('For', 'IN'),
 ('lined', 'JJ'),
 ('macro', 'NN'),
 ('mode', 'NN'),
 ('Macro', 'NNP'),
 ('mode', 'NN'),
 ('feature', 'NN'),
 ('smartphones', 'NNS'),
 ('But', 'CC'),
 ('There', 'EX'),
 ('Macro', 'NNP'),
 ('mode', 'NN'),
 ('camera', 'NN'),
 ('app', 'NN'),
 ('But', 'CC'),
 ('camera', 'NN'),
 ('close', 'RB'),
 ('subject', 'JJ'),
 ('switches', 'NNS'),
 ('ultra-wide', 'JJ'),
 ('lens', 'NNS'),
 ('switches', 'NNS'),
 ('macro.•', 'VBP'),
 ('results', 'NNS'),
 ('possibly', 'RB'),
 ('close-up', 'JJ'),
 ('shots', 'NNS'),
 ('smartphone', 'NN'),
 ('But', 'CC'),
 ('light', 'NN'),
 ('Also', 'RB'),
 ('noticed', 'VBD'),
 ('images', 'NNS'),
 ('sharp', 'JJ'),
 ('focal', 'JJ'),
 ('point', 'NN'),
 ('’', 'NNP'),
 ('perfect', 'NN'),
 ('’', 'NNP'),
 ('shot', 'VBD'),
 ('ultra-wide', 'JJ'),
 ('lens•', 'IN'),
 ('These', 'DT'),
 ('days', 'NNS'),
 ('’', 'VBP'),
 ('smartphone', 'NN'),
 ('We', 'PRP'),
 ('buy', 'VBP'),
 ('smartphones', 'NNS'),
 ('plethora', 'VBP'),
 ('original', 'JJ'),
 ('making', 'NN'),
 ('voice', 'NN'),
 ('relegated', 'VBD'),
 ('sidelines', 'NNS'),
 ('In', 'IN'),
 ('fact', 'NN'),
 ('smartphones', 'NNS'),
 ('days', 'NNS'),
 ('smart', 'VBP'),
 ('powerful', 'JJ'),
 ('buy', 'VB'),
 ('devices', 'NNS'),
 ('primarily', 'RB'),
 ('bothering', 'VBG'),
 ('add', 'VB'),
 ('SIM', 'NNP'),
 ('card', 'JJ'),
 ('purchase', 'NN'),
 ('There', 'EX'),
 ('smartphone', 'JJ'),
 ('ability', 'NN'),
 ('push', 'NN'),
 ('limits', 'NNS'),
 ('adding', 'VBG'),
 ('convenience', 'NN'),
 ('eases', 'NNS'),
 ('workflows', 'VBZ'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('aimed', 'VBD'),
 ('set', 'VBN'),
 ('users.•', 'JJ'),
 ('camera', 'NN'),
 ('magic', 'NN'),
 ('notch', 'NN'),
 ('switch', 'NN'),
 ('video', 'NN'),
 ('unleashed', 'VBD'),
 ('processing', 'VBG'),
 ('power', 'NN'),
 ('tandem', 'NN'),
 ('lenses', 'VBZ'),
 ('computational', 'JJ'),
 ('photography', 'NN'),
 ('algorithms', 'NN'),
 ('offer', 'VBP'),
 ('Cinematic', 'JJ'),
 ('Mode', 'NNP'),
 ('This', 'DT'),
 ('mode', 'NN'),
 ('thousands', 'NNS'),
 ('movie', 'NN'),
 ('scenes', 'NNS'),
 ('’', 'VBP'),
 ('trained', 'JJ'),
 ('shift', 'NN'),
 ('focus', 'NN'),
 ('subject', 'JJ'),
 ('attention', 'NN'),
 ('gaze', 'NN'),
 ('subject', 'JJ'),
 ('shifts', 'NNS'),
 ('Doing', 'VBG'),
 ('movie', 'NN'),
 ('cameras', 'NNS'),
 ('tough', 'JJ'),
 ('automatically', 'RB'),
 ('And', 'CC'),
 ('’', 'JJ'),
 ('change', 'NN'),
 ('editing', 'VBG'),
 ('video', 'NN'),
 ('post', 'NN'),
 ('process', 'NN'),
 ('All', 'DT'),
 ('mind-boggling', 'NN'),
 ('stuff.There', 'RB'),
 ('weapon', 'VBZ'),
 ('’', 'JJ'),
 ('quiver', 'NN'),
 ('ProRes', 'NNP'),
 ('RAW', 'NNP'),
 ('format', 'NN'),
 ('video.What', 'WP'),
 ('camera', 'NN'),
 ('capabilities', 'VBZ'),
 ('viable', 'JJ'),
 ('replacement', 'NN'),
 ('lot', 'NN'),
 ('professional', 'JJ'),
 ('video', 'NN'),
 ('cameras', 'NNS'),
 ('So', 'RB'),
 ('creator', 'JJ'),
 ('videos', 'NN'),
 ('camera', 'NN'),
 ('buy', 'VB'),
 ('Yes', 'NNP'),
 ('cameras', 'NNS'),
 ('edit', 'NN'),
 ('captures', 'NNS'),
 ('And', 'CC'),
 ('upload', 'JJ'),
 ('Internet', 'NNP'),
 ('’', 'NNP'),
 ('output', 'NN'),
 ('That', 'WDT'),
 ('’', 'JJ'),
 ('Pro', 'NNP'),
 ('starts', 'VBZ'),
 ('making', 'VBG'),
 ('sense.It', 'JJ'),
 ('’', 'JJ'),
 ('branding', 'VBG'),
 ('’', 'JJ'),
 ('calling', 'VBG'),
 ('card.•', 'NN'),
 ('There', 'EX'),
 ('set', 'VBN'),
 ('users', 'NNS'),
 ('Pro', 'NNP'),
 ('inside', 'IN'),
 ('Yes', 'NNP'),
 ('gamers', 'NNS'),
 ('love', 'VBP'),
 ('ProMotion', 'NNP'),
 ('adaptive', 'JJ'),
 ('refresh', 'NN'),
 ('rate', 'NN'),
 ('Again', 'NNP'),
 ('things', 'NNS'),
 ('differently', 'RB'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('switch', 'FW'),
 ('10Hz', 'CD'),
 ('refresh', 'JJ'),
 ('rate', 'NN'),
 ('120Hz', 'CD'),
 ('content', 'NN'),
 ('demands', 'NNS'),
 ('And', 'CC'),
 ('’', 'NNP'),
 ('user', 'NNP'),
 ('decide', 'VB'),
 ('She', 'PRP'),
 ('leave', 'VB'),
 ('complex', 'JJ'),
 ('decision-making', 'NN'),
 ('A15', 'NNP'),
 ('Bionic', 'NNP'),
 ('powers', 'NNS'),
 ('phone.•', 'VBP'),
 ('Frankly', 'NNP'),
 ('regular', 'JJ'),
 ('stuff', 'NN'),
 ('’', 'NN'),
 ('figure', 'NN'),
 ('happening', 'VBG'),
 ('display', 'NN'),
 ('That', 'WDT'),
 ('’', 'VBZ'),
 ('smooth', 'RB'),
 ('But', 'CC'),
 ('start', 'VBP'),
 ('playing', 'VBG'),
 ('games', 'NNS'),
 ('Thumper', 'NNP'),
 ('Pocket', 'NNP'),
 ('Edition+', 'NNP'),
 ('difference', 'NN'),
 ('renders', 'NNS'),
 ('game', 'NN'),
 ('compared', 'VBN'),
 ('earlier', 'RBR'),
 ('generations', 'NNS'),
 ('Remember', 'NNP'),
 ('extra', 'JJ'),
 ('graphics', 'NNS'),
 ('core', 'VBP'),
 ('solely', 'RB'),
 ('videos.•', 'VBP'),
 ('So', 'RB'),
 ('powerful', 'JJ'),
 ('Well', 'NNP'),
 ('powerful', 'JJ'),
 ('edit', 'RB'),
 ('4K', 'CD'),
 ('videos', 'NNS'),
 ('change', 'VBP'),
 ('focus', 'VB'),
 ('All', 'DT'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('power', 'NN'),
 ('guzzler', 'NN'),
 ('beauty', 'NN'),
 ('offers', 'VBZ'),
 ('life', 'NN'),
 ('this.In', 'NN'),
 ('fact', 'NN'),
 ('review', 'VB'),
 ('period', 'NN'),
 ('36', 'CD'),
 ('hours', 'NNS'),
 ('charging', 'VBG'),
 ('upto', 'JJ'),
 ('100', 'CD'),
 ('10', 'CD'),
 ('left', 'VBD'),
 ('Crazy', 'NNP'),
 ('What', 'WP'),
 ('’', 'VBD'),
 ('•', 'JJ'),
 ('``', '``'),
 ('Tax', 'NNP'),
 ("''", "''"),
 ('That\\', 'NNP'),
 ('unscrupulous', 'JJ'),
 ('money', 'NN'),
 ('demanded', 'VBD'),
 ('Apple.•', 'NNP'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('superb', 'NN'),
 ('pulls', 'NNS'),
 ('punches', 'VBZ'),
 ('expecting', 'VBG'),
 ('features', 'NNS'),
 ('blow', 'IN'),
 ('mind', 'NN'),
 ('change', 'NN'),
 ('life', 'NN'),
 ('daily', 'JJ'),
 ('basis', 'NN'),
 ('Cinematic', 'NNP'),
 ('Mode', 'NNP'),
 ('testament', 'NN'),
 ('powerful', 'JJ'),
 ('smartphones', 'NNS'),
 ('’', 'JJ'),
 ('feature', 'NN'),
 ('’', 'VBZ'),
 ('regular', 'JJ'),
 ('people', 'NNS'),
 ('Of', 'IN'),
 ('wedding', 'VBG'),
 ('photographers', 'NNS'),
 ('creators', 'NNS'),
 ('thrilled', 'VBD'),
 ('executive', 'NN'),
 ('’', 'NN'),
 ('upgrading', 'VBG'),
 ('phone.•', 'NN'),
 ('In', 'IN'),
 ('sense', 'NN'),
 ('improved', 'JJ'),
 ('life', 'NN'),
 ('feature', 'NN'),
 ('impacts', 'VBZ'),
 ('number', 'NN'),
 ('people', 'NNS'),
 ('point', 'VBP'),
 ('big', 'JJ'),
 ('change', 'NN'),
 ('disruptor', 'NN'),
 ('incremental', 'JJ'),
 ('And', 'CC'),
 ('running', 'VBG'),
 ('20W', 'CD'),
 ('charger.Should', 'JJ'),
 ('buy', 'VB'),
 ('13', 'CD'),
 ('Pro', 'NNP'),
 ('But', 'CC'),
 ('buy', 'VB'),
 ('No', 'NNP'),
 ('That', 'NNP'),
 ('’', 'VBD'),
 ('Pro', 'NNP'),
 ('issues', 'NNS'),
 ('13', 'CD'),
 ('regular', 'JJ'),
 ('users', 'NNS'),
 ('Pro', 'NNP'),
 ('aimed', 'VBD'),
 ('camera', 'NN'),
 ('display', 'NN'),
 ('graphics', 'NNS'),
 ('power', 'NN'),
 ('If', 'IN'),
 ('creator', 'NN'),
 ('developer', 'NN'),
 ('working', 'VBG'),
 ('cutting-edge', 'JJ'),
 ('apps', 'JJ'),
 ('must-have', 'JJ'),
 ('Regular', 'JJ'),
 ('people', 'NNS'),
 ('buy', 'VBP'),
 ('world', 'NN'),
 ('ahead', 'RB'),
 ('race', 'NN'),
 ('own.And', 'JJ'),
 ('max', 'RBS'),
 ('line-up', 'JJ'),
 ('punch', 'NN'),
 ('hole', 'NN'),
 ('pocket', 'NN'),
 ('deep', 'JJ'),
 ('reach', 'NN'),
 ('kidney', 'NN'),
 ('That', 'IN'),
 ('’', 'JJ'),
 ('hurt', 'NN'),
 ('“', 'VBD'),
 ('filthy-rich', 'JJ'),
 ('”', 'NNP'),
 ('though.Didn', 'NN'),
 ('’', 'NNP'),
 ('spam', 'NN'),
 ('gallery', 'NN'),
 ('“', 'NN'),
 ('unboxing', 'VBG'),
 ('”', 'NNP'),
 ('“', 'NNP'),
 ('swiveling', 'VBG'),
 ('”', 'JJ'),
 ('“', 'JJ'),
 ('showing-off', 'NN'),
 ('”', 'NNP'),
 ('phone…as', 'NN'),
 ('users', 'NNS'),
 ('Accessories', 'NNPS'),
 ('However', 'RB'),
 ('’', 'RB'),
 ('attaching', 'VBG'),
 ('image', 'NN'),
 ('accessories', 'NNS'),
 ('bundled', 'VBD'),
 ('left', 'JJ'),
 ('transit', 'NN'),
 ('Also', 'RB'),
 ('linking', 'VBG'),
 ('check', 'NN'),
 ('•', 'NNP'),
 ('USB', 'NNP'),
 ('3.0', 'CD'),
 ('OTG', 'NNP'),
 ('Adapter', 'NNP'),
 ('Cable', 'NNP'),
 ('//www.amazon.in/gp/product/B097JQN64T/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Spigen', 'NNP'),
 ('Smart', 'NNP'),
 ('Fold', 'NNP'),
 ('Magnetic', 'NNP'),
 ('Wallet', 'NNP'),
 ('Card', 'NNP'),
 ('Holder', 'NNP'),
 ('Designed', 'NNP'),
 ('MagSafe', 'NNP'),
 ('Kickstand', 'NNP'),
 ('//www.amazon.in/gp/product/B08S1XM54D/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'JJ'),
 ('psc=1•', 'NN'),
 ('USB-C', 'NNP'),
 ('Lightning', 'NNP'),
 ('Cable', 'NNP'),
 ('20', 'CD'),
 ('cm', 'NN'),
 ('MFi-Certified', 'NNP'),
 ('PD', 'NNP'),
 ('Fast', 'NNP'),
 ('Charging', 'NNP'),
 ('Cable', 'NNP'),
 ('//www.amazon.in/gp/product/B07WVXGFCJ/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('0.5', 'CD'),
 ('Feet', 'NNP'),
 ('Short', 'NNP'),
 ('Lightning', 'NNP'),
 ('USB', 'NNP'),
 ('Data', 'NNP'),
 ('Sync', 'NNP'),
 ('Cable', 'NNP'),
 ('MFi', 'NNP'),
 ('Certified', 'NNP'),
 ('//www.amazon.in/gp/product/B01FCUJCLA/ref=ppx_od_dt_b_asin_title_s00',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Magnetic', 'NNP'),
 ('Compatible', 'NNP'),
 ('Case', 'NNP'),
 ('Back', 'NNP'),
 ('Cover', 'NNP'),
 ('Magnetic', 'NNP'),
 ('Wireless', 'NNP'),
 ('Charging', 'NNP'),
 ('Anti-Fingerprint', 'NNP'),
 ('Shockproof', 'NNP'),
 ('Bumper', 'NNP'),
 ('//www.amazon.in/gp/product/B09CRVQCH5/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Denim', 'NNP'),
 ('Flip', 'NNP'),
 ('Cover', 'NNP'),
 ('Premium', 'NNP'),
 ('Luxury', 'NNP'),
 ('Slim', 'NNP'),
 ('Wallet', 'NNP'),
 ('Folio', 'NNP'),
 ('Case', 'NNP'),
 ('Magnetic', 'NNP'),
 ('Cover', 'NNP'),
 ('//www.amazon.in/gp/product/B094FHN47Q/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'JJ'),
 ('psc=1•', 'NN'),
 ('Privacy', 'NNP'),
 ('Tempered', 'NNP'),
 ('Glass', 'NNP'),
 ('Screen', 'NNP'),
 ('Protector', 'NNP'),
 ('//www.amazon.in/gp/product/B09GBP2NXX/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1', 'NN'),
 ('image', 'NN'),
 ('Bought', 'NNP'),
 ('•', 'NNP'),
 ('Magnetic', 'NNP'),
 ('Wireless', 'NNP'),
 ('Charging', 'NNP'),
 ('Conversion', 'NNP'),
 ('Kit', 'NNP'),
 ('//www.amazon.in/gp/product/B08S6XQFDM/ref=ppx_yo_dt_b_asin_title_o00_s00',
  'NNP'),
 ('ie=UTF8', 'JJ'),
 ('psc=1•', 'NN'),
 ('Mag-Safe', 'NNP'),
 ('Magnetic', 'NNP'),
 ('Phone', 'NNP'),
 ('Holder', 'NNP'),
 ('Leather', 'NNP'),
 ('Pad', 'NNP'),
 ('//www.amazon.in/gp/product/B08RDX7GZ5/ref=ppx_yo_dt_b_asin_title_o00_s00',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1', 'NN'),
 ('Creating', 'NNP'),
 ('collage', 'NN'),
 ('stuffs', 'NNS'),
 ('reference', 'NN'),
 ('11.11.2021', 'CD'),
 ('Also', 'RB'),
 ('added', 'VBD'),
 ('arsenal', 'JJ'),
 ('•', 'NNP'),
 ('Metal', 'NNP'),
 ('Bumper', 'NNP'),
 ('//www.amazon.in/gp/product/B09FZKKPLM/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Magsafe', 'NNP'),
 ('holder', 'NN'),
 ('Laptop', 'NNP'),
 ('//www.amazon.in/gp/product/B095YY319F/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('USB', 'NNP'),
 ('C', 'NNP'),
 ('USB', 'NNP'),
 ('A', 'NNP'),
 ('//www.amazon.in/gp/product/B0963ZXFHJ/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Camera', 'NNP'),
 ('Module', 'NNP'),
 ('Guard', 'NNP'),
 ('//www.amazon.in/gp/product/B09H36MHF6/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1•', 'NN'),
 ('Charging', 'VBG'),
 ('Station', 'NNP'),
 ('//www.amazon.in/gp/product/B096FNG2MJ/ref=ppx_yo_dt_b_search_asin_title',
  'NNP'),
 ('ie=UTF8', 'NN'),
 ('psc=1', 'NN'),
 ('That\\', 'NNP'),
 ('folks', 'NNS'),
 ('\\n\\n', 'VBP'),
 ("'\\n\\n", 'CD'),
 ('Need', 'NNP'),
 ('camera', 'NN'),
 ('software', 'NN'),
 ('update', 'JJ'),
 ('rest', 'NN'),
 ('fine.\\n\\n', 'NN'),
 ("'\\n\\n\\n\\n\\n", 'POS'),
 ('media', 'NNS'),
 ('loaded.\\n', 'VBP'),
 ('\\n\\n\\n\\n\\n', 'JJ'),
 ('\\xa0Best', 'NNP'),
 ('💙', 'NNP'),
 ('blue', 'VBD'),
 ('colour', 'JJ'),
 ('awesome', 'JJ'),
 ('..', 'NN'),
 ('BEAST', 'NNP'),
 ('💙🍎\\n\\n', 'NNP'),
 ('``', '``'),
 ('\\n\\n', 'NNP'),
 ('According', 'VBG'),
 ('guysFirst', 'RB'),
 ('purchased', 'VBN'),
 ('iPhoneSecondly', 'RB'),
 ('budget', 'NN'),
 ('1lakhs', 'CD'),
 ('spending', 'NN'),
 ('worth', 'JJ'),
 ('allInfact', 'JJ'),
 ('invest', 'JJS'),
 ('money', 'NN'),
 ('stock', 'NN'),
 ('stock', 'NN'),
 ('money', 'NN'),
 ('doubled', 'VBD'),
 ('future', 'JJ'),
 ('bcoz', 'NN'),
 ('buying', 'VBG'),
 ('depreciating', 'VBG'),
 ('assetHope', 'NN'),
 ('understand', 'NN'),
 ('🙂\\n\\n', 'NN'),
 ("''", "''"),
 ("'\\n\\n\\n\\n\\n", 'CC'),
 ('media', 'NNS'),
 ('loaded.\\n', 'VBP'),
 ('\\n\\n\\n\\n\\n', 'SYM'),
 ('\\xa0The', 'JJ'),
 ('excellent', 'JJ'),
 ('Samsung', 'NNP'),
 ('galaxy', 'NN'),
 ('21', 'CD'),
 ('ultra', 'JJ'),
 ('macro', 'NN'),
 ('photography', 'NN'),
 ('After', 'IN'),
 ('announced', 'JJ'),
 ('macro', 'NN'),
 ('photography', 'NN'),
 ('ability', 'NN'),
 ('decided', 'VBD'),
 ('blindfoldedly', 'RB'),
 ('delivery', 'NN'),
 ('delayed', 'JJ'),
 ('demand', 'NN'),
 ('supply', 'NN'),
 ('difference', 'NN'),
 ('worth', 'JJ'),
 ('wait', 'JJ'),
 ('thing', 'NN'),
 ('glass', 'NN'),
 ('shield', 'VBD'),
 ('cover', 'RB'),
 ('thought', 'VBN'),
 ('kill', 'VB'),
 ('nice', 'JJ'),
 ('iOS', 'JJ'),
 ('Simple', 'NNP'),
 ('settings.\\n\\n', 'NN'),
 ('``', '``'),
 ('\\n\\n', 'NNP'),
 ('previously', 'RB'),
 ('owned', 'VBD'),
 ('12', 'CD'),
 ('Pro', 'NNP'),
 ('shifted', 'VBD'),
 ('13', 'CD'),
 ('boy', 'NN'),
 ('disappointed', 'VBD'),
 ('What', 'WP'),
 ('loved', 'VBD'),
 ('camera', 'NN'),
 ('pic', 'NN'),
 ('attached', 'VBD'),
 ('night', 'NN'),
 ('photography', 'NN'),
 ('pic', 'NN'),
 ('uploaded', 'VBD'),
 ('shot', 'JJ'),
 ('7', 'CD'),
 ('pm', 'JJ'),
 ('Apart', 'NNP'),
 ('camera', 'NN'),
 ('refresh', 'NN'),
 ('rate', 'NN'),
 ('scrolling', 'VBG'),
 ('supported', 'VBN'),
 ('apps', 'NN'),
 ('giving', 'VBG'),
 ('lag', 'NN'),
 ('input', 'NN'),
 ('Overall', 'NNP'),
 ('choose', 'VBP'),
 ('smartphone', 'NN'),
 ('super', 'JJ'),
 ('money', 'NN'),
 ('spent', 'VBN'),
 ('cost', 'NN'),
 ('it.\\n\\n', 'NN'),
 ("''", "''"),
 ("'\\n\\n", 'POS'),
 ('With', 'IN'),
 ('incremental', 'JJ'),
 ('improvements', 'NNS'),
 ('areas', 'NNS'),
 ('matter', 'VBP'),
 ('camera', 'NN'),
 ('display', 'NN'),
 ('beast', 'NN'),
 ('iPhone.\\n\\n', 'NN'),
 ("'\\n\\n", 'POS'),
 ('Well', 'NNP'),
 ('switched', 'VBD'),
 ('One', 'CD'),
 ('Now', 'RB'),
 ('fact', 'NN'),
 ('dream', 'NN'),
 ('So', 'NNP'),
 ('bought', 'VBD'),
 ('Everything', 'NNP'),
 ('marvellous', 'JJ'),
 ('..', 'NNP'),
 ('technical', 'JJ'),
 ('reviews', 'NNS'),
 ('write', 'VBP'),
 ('again…', 'JJ'),
 ('Comparing', 'NNP'),
 ('ios', 'NNS'),
 ('sense', 'NN'),
 ('completely', 'RB'),
 ('platform', 'JJ'),
 ('purpose', 'RB'),
 ('Various', 'JJ'),
 ('people', 'NNS'),
 ('gave', 'VBD'),
 ('reviews', 'NNS'),
 ('comparing', 'VBG'),
 ('practical…', 'NN'),
 ('understand', 'JJ'),
 ('money', 'NN'),
 ('..', 'NN'),
 ('wont', 'VBP'),
 ('regret\\n\\n', 'NN'),
 ("'\\n\\n", 'NN'),
 ('This', 'DT'),
 ('earlier', 'JJR'),
 ('iPhones', 'NNS'),
 ('’', 'NNP'),
 ('backup', 'NN'),
 ('13', 'CD'),
 ('max', 'NN'),
 ('completely', 'RB'),
 ('changed', 'VBN'),
 ('view', 'NN'),
 ('feel', 'NN'),
 ('aspects.\\n\\n', 'IN'),
 ("'\\n\\n", 'IN'),
 ('It', 'PRP'),
 ('elevates', 'VBZ'),
 ('great', 'JJ'),
 ('Iphone', 'NNP'),
 ('experience', 'NN'),
 ('motion', 'NN'),
 ('display', 'NN'),
 ('excellent', 'JJ'),
 ('camera', 'NN'),
 ('\\n\\n', 'VBZ'),
 ('``', '``'),
 ('\\n\\n\\n\\n\\n', 'JJ'),
 ('media', 'NNS'),
 ('loaded.\\n', 'VBP'),
 ('\\n\\n\\n\\n\\n', 'JJ'),
 ('\\xa0I', 'NNP'),
 ('switched', 'VBD'),
 ('11', 'CD'),
 ('max', 'NN'),
 ('13', 'CD'),
 ('max', 'NN'),
 ('As', 'IN'),
 ('experience', 'NN'),
 ('simple', 'JJ'),
 ('Yes', 'NNP'),
 ('expensive', 'JJ'),
 ('sight', 'NN'),
 ('set', 'VBN'),
 ('buy.Pros', 'NNS'),
 ('Display', 'NNP'),
 ('gorgeous', 'JJ'),
 ('120Hz', 'CD'),
 ('Premium', 'JJ'),
 ('delivers', 'NNS'),
 ('it.', 'VBP'),
 ('Battery', 'NNP'),
 ('life', 'NN'),
 ('unbelievable', 'JJ'),
 ('drain', 'NN'),
 ('single', 'JJ'),
 ('ending', 'VBG'),
 ('30~35', 'CD'),
 ('end', 'NN'),
 ('Build', 'NNP'),
 ('quality', 'NN'),
 ('unquestionably', 'RB'),
 ('Solid', 'NNP'),
 ('Beautiful.', 'NNP'),
 ('New', 'NNP'),
 ('camera', 'NN'),
 ('setup', 'NN'),
 ('phones', 'NNS'),
 ('andunquestionably', 'RB'),
 ('Video', 'NNP'),
 ('recording', 'VBG'),
 ('usual', 'JJ'),
 ('Finally', 'RB'),
 ('3x', 'CD'),
 ('zoom', 'NN'),
 ('makes', 'VBZ'),
 ('zoom', 'NN'),
 ('scenes', 'NNS'),
 ('past', 'IN'),
 ('iPhones', 'NNS'),
 ('Flat', 'NNP'),
 ('helps', 'VBZ'),
 ('applying', 'VBG'),
 ('protector', 'NN'),
 ('general.', 'NN'),
 ('Performance', 'NNP'),
 ('Smartphone', 'NNP'),
 ('lag', 'NN'),
 ('hiccup', 'NN'),
 ('gameplay', 'NN'),
 ('time.Cons', 'NNS'),
 ('Price', 'NNP'),
 ('Yes', 'NNP'),
 ('extremely', 'RB'),
 ('expensive', 'JJ'),
 ('India', 'NNP'),
 ('Flagships', 'NNP'),
 ('Samsung', 'NNP'),
 ('touched', 'VBD'),
 ('prices', 'NNS'),
 ('factor', 'NN'),
 ('about.', 'VBP'),
 ('Heaviest', 'NNP'),
 ('240', 'CD'),
 ('grams', 'NNS'),
 ('lot', 'NN'),
 ('weight', 'NN'),
 ('means', 'VBZ'),
 ('build', 'JJ'),
 ('solid', 'JJ'),
 ('huge', 'JJ'),
 ('too.', 'NN'),
 ('Unconventional', 'NNP'),
 ('dual', 'JJ'),
 ('sim', 'NN'),
 ('style', 'NN'),
 ('Physical', 'NNP'),
 ('SIM', 'NNP'),
 ('eSIM', 'JJ'),
 ('issue', 'NN'),
 ('users', 'NNS'),
 ('2', 'CD'),
 ('physical', 'JJ'),
 ('SIM', 'NNP'),
 ('cards.', 'NN'),
 ('Usual', 'NNP'),
 ('limitations', 'NNS'),
 ('iOS', 'VBP'),
 ('lime', 'JJ'),
 ('lack', 'NN'),
 ('customisation', 'NN'),
 ('Android', 'NNP'),
 ('users', 'NNS'),
 ('love', 'VBP'),
 ('point', 'NN'),
 ('limitations', 'NNS'),
 ('deal', 'VBP'),
 ('breakers.\\n\\n', 'NN'),
 ("''", "''"),
 ('``', '``'),
 ('\\n\\n', 'NNP'),
 ('skeptical', 'JJ'),
 ('genuineness', 'NN'),
 ('receive', 'JJ'),
 ('stock', 'NN'),
 ('stores', 'NNS'),
 ('So', 'RB'),

In [149]:
#library to correct the spelling


#!pip install autocorrect
from autocorrect import Speller # Library to check typos
spell = Speller(lang='en') # supported languages: en, pl, ru, uk, tr, es
spell

x=spell('oncee')
x
#now how to  apply in the data
sentence3 = "Ntural Luanguage Processin deals with the art of extracting insightes from Natural Languaes"
correct_wrd=[]
tk=nltk.word_tokenize(sentence3)
tk

correct_wrd=[]
for i in tk:
    #print(i)
    zz=spell(i) 
    correct_wrd.append(zz)
    
    print(zz)

Natural
Language
Processing
deals
with
the
art
of
extracting
insights
from
Natural
Languages

Stemmer	Aggressiveness	Language Support	Returns Real Words?	Best For

Porter	Moderate	 English_only	 No	Basic NLP tasks
Lancaster	High	 English_only	 No	Very short stems
Snowball	Moderate Many	         No	Recommended stemmer
Regex-based	Custom	 N/A	         No	Simple rule-based tasks
Lemmatizer	Low	     Yes	         Yes	When meaning matters

## Stemming and Lemmatization


🌱 Stemming
Cuts the word to its root — fast but rough.
Might give broken words.
👉 "studies" → "studi"


📚 Lemmatization
Finds the real dictionary word (base form).
Smarter and cleaner.
👉 "studies" → "study"

There are 3 types of stemmers
1. PorterStemmer
2. LancasterStemmer
3. SnowballStemmer (also called Porter2)
4. Regex-based Stemmer

In [84]:
from nltk.stem import PorterStemmer,LancasterStemmer,SnowballStemmer
lanc=LancasterStemmer()
port=PorterStemmer()
snow=SnowballStemmer("english")

In [85]:
print(snow.stem("engineering"))
print(port.stem("engineering"))
print(snow.stem("engineering"))

engin
engin
engin

* Lemmatization


Lemmatization also does the same thing as stemming and try to bring a word to its base form, but unlike stemming it do keep in account the actual meaning of the base word i.e. the base word belongs to any specific language. The ‘base word’ is known as ‘Lemma’.

We use WordNet Lemmatizer for Lemmatization in nltk.

In [86]:
from nltk.stem import WordNetLemmatizer

In [87]:
wl=WordNetLemmatizer()


print(wl.lemmatize("engineering",pos='v')) #engineer
print(wl.lemmatize("engineering"))#engineering

engineer
engineering

In [88]:
#now lemmetizing it on my cleaned data
from nltk.stem import WordNetLemmatizer

lm=WordNetLemmatizer()

lemma_sent=[]

for i in clean_data:
    x=lm.lemmatize(i)
    lemma_sent.append(x)


print(lemma_sent)

## simillarly we can do it for stemmer

["'\\n\\n", 'Update', '13.121.2021', 'added', 'unnecessary/money-wasting', 'accessory', 'Samsung', 'Does', 'RIGHT', 'So', 'switched', 'Android', 'Galaxy', 'Note', 'user', '2015', 'upgrading', 'year', 'Note', '7', '…The', '13', 'Pro', 'design', 'similar', '12', 'Pro', '—', 'discernible', 'change', 'thicker', 'camera', 'bump', 'larger', 'square', 'This', 'highlight', 'significant', 'change', 'past', 'year.On', 'display', 'notch', 'smaller', 'But', 'mean', 'year', 'display', 'real', 'estate', 'fix', 'Strangely', 'felt', '13', 'Pro', 'weighed', 'lot…240', 'gram', 'Will', 'run', 'spec-sheet', 'Readily', 'online', 'What', '’', 'Let', 'thing', 'straight', 'It', 'pointless', 'talking', 'feature', 'flagship', 'They', 'expect', 'tab', 'anticipated', 'So', 'design', 'actual', 'processing', 'power', 'top-notch', 'But', 'expect', 'top-end', 'A', 'top-end', 'cost', 'top-end', 'laptop', 'company.So', '’', 'feature', 'new.•', 'On', '13', 'Pro', 'literally', 'flexing', 'camera', 'muscle', 'big', 'bump', 'muscle', 'lens', 'larger', 'deeper', 'clear', 'indication', 'camera', 'take', 'light', 'performs', 'low', 'light.•', 'All', 'translates', 'photo', 'compared', 'generation', 'Pro', 'phone', 'There', 'greater', 'clarity', 'low', 'light', 'character', 'click.•', 'But', '’', 'sell', 'For', 'lined', 'macro', 'mode', 'Macro', 'mode', 'feature', 'smartphones', 'But', 'There', 'Macro', 'mode', 'camera', 'app', 'But', 'camera', 'close', 'subject', 'switch', 'ultra-wide', 'lens', 'switch', 'macro.•', 'result', 'possibly', 'close-up', 'shot', 'smartphone', 'But', 'light', 'Also', 'noticed', 'image', 'sharp', 'focal', 'point', '’', 'perfect', '’', 'shot', 'ultra-wide', 'lens•', 'These', 'day', '’', 'smartphone', 'We', 'buy', 'smartphones', 'plethora', 'original', 'making', 'voice', 'relegated', 'sideline', 'In', 'fact', 'smartphones', 'day', 'smart', 'powerful', 'buy', 'device', 'primarily', 'bothering', 'add', 'SIM', 'card', 'purchase', 'There', 'smartphone', 'ability', 'push', 'limit', 'adding', 'convenience', 'eas', 'workflow', '13', 'Pro', 'aimed', 'set', 'users.•', 'camera', 'magic', 'notch', 'switch', 'video', 'unleashed', 'processing', 'power', 'tandem', 'lens', 'computational', 'photography', 'algorithm', 'offer', 'Cinematic', 'Mode', 'This', 'mode', 'thousand', 'movie', 'scene', '’', 'trained', 'shift', 'focus', 'subject', 'attention', 'gaze', 'subject', 'shift', 'Doing', 'movie', 'camera', 'tough', 'automatically', 'And', '’', 'change', 'editing', 'video', 'post', 'process', 'All', 'mind-boggling', 'stuff.There', 'weapon', '’', 'quiver', 'ProRes', 'RAW', 'format', 'video.What', 'camera', 'capability', 'viable', 'replacement', 'lot', 'professional', 'video', 'camera', 'So', 'creator', 'video', 'camera', 'buy', 'Yes', 'camera', 'edit', 'capture', 'And', 'upload', 'Internet', '’', 'output', 'That', '’', 'Pro', 'start', 'making', 'sense.It', '’', 'branding', '’', 'calling', 'card.•', 'There', 'set', 'user', 'Pro', 'inside', 'Yes', 'gamers', 'love', 'ProMotion', 'adaptive', 'refresh', 'rate', 'Again', 'thing', 'differently', '13', 'Pro', 'switch', '10Hz', 'refresh', 'rate', '120Hz', 'content', 'demand', 'And', '’', 'user', 'decide', 'She', 'leave', 'complex', 'decision-making', 'A15', 'Bionic', 'power', 'phone.•', 'Frankly', 'regular', 'stuff', '’', 'figure', 'happening', 'display', 'That', '’', 'smooth', 'But', 'start', 'playing', 'game', 'Thumper', 'Pocket', 'Edition+', 'difference', 'render', 'game', 'compared', 'earlier', 'generation', 'Remember', 'extra', 'graphic', 'core', 'solely', 'videos.•', 'So', 'powerful', 'Well', 'powerful', 'edit', '4K', 'video', 'change', 'focus', 'All', '13', 'Pro', 'power', 'guzzler', 'beauty', 'offer', 'life', 'this.In', 'fact', 'review', 'period', '36', 'hour', 'charging', 'upto', '100', '10', 'left', 'Crazy', 'What', '’', '•', '``', 'Tax', "''", 'That\\', 'unscrupulous', 'money', 'demanded', 'Apple.•', '13', 'Pro', 'superb', 'pull', 'punch', 'expecting', 'feature', 'blow', 'mind', 'change', 'life', 'daily', 'basis', 'Cinematic', 'Mode', 'testament', 'powerful', 'smartphones', '’', 'feature', '’', 'regular', 'people', 'Of', 'wedding', 'photographer', 'creator', 'thrilled', 'executive', '’', 'upgrading', 'phone.•', 'In', 'sense', 'improved', 'life', 'feature', 'impact', 'number', 'people', 'point', 'big', 'change', 'disruptor', 'incremental', 'And', 'running', '20W', 'charger.Should', 'buy', '13', 'Pro', 'But', 'buy', 'No', 'That', '’', 'Pro', 'issue', '13', 'regular', 'user', 'Pro', 'aimed', 'camera', 'display', 'graphic', 'power', 'If', 'creator', 'developer', 'working', 'cutting-edge', 'apps', 'must-have', 'Regular', 'people', 'buy', 'world', 'ahead', 'race', 'own.And', 'max', 'line-up', 'punch', 'hole', 'pocket', 'deep', 'reach', 'kidney', 'That', '’', 'hurt', '“', 'filthy-rich', '”', 'though.Didn', '’', 'spam', 'gallery', '“', 'unboxing', '”', '“', 'swiveling', '”', '“', 'showing-off', '”', 'phone…as', 'user', 'Accessories', 'However', '’', 'attaching', 'image', 'accessory', 'bundled', 'left', 'transit', 'Also', 'linking', 'check', '•', 'USB', '3.0', 'OTG', 'Adapter', 'Cable', '//www.amazon.in/gp/product/B097JQN64T/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Spigen', 'Smart', 'Fold', 'Magnetic', 'Wallet', 'Card', 'Holder', 'Designed', 'MagSafe', 'Kickstand', '//www.amazon.in/gp/product/B08S1XM54D/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'USB-C', 'Lightning', 'Cable', '20', 'cm', 'MFi-Certified', 'PD', 'Fast', 'Charging', 'Cable', '//www.amazon.in/gp/product/B07WVXGFCJ/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', '0.5', 'Feet', 'Short', 'Lightning', 'USB', 'Data', 'Sync', 'Cable', 'MFi', 'Certified', '//www.amazon.in/gp/product/B01FCUJCLA/ref=ppx_od_dt_b_asin_title_s00', 'ie=UTF8', 'psc=1•', 'Magnetic', 'Compatible', 'Case', 'Back', 'Cover', 'Magnetic', 'Wireless', 'Charging', 'Anti-Fingerprint', 'Shockproof', 'Bumper', '//www.amazon.in/gp/product/B09CRVQCH5/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Denim', 'Flip', 'Cover', 'Premium', 'Luxury', 'Slim', 'Wallet', 'Folio', 'Case', 'Magnetic', 'Cover', '//www.amazon.in/gp/product/B094FHN47Q/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Privacy', 'Tempered', 'Glass', 'Screen', 'Protector', '//www.amazon.in/gp/product/B09GBP2NXX/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1', 'image', 'Bought', '•', 'Magnetic', 'Wireless', 'Charging', 'Conversion', 'Kit', '//www.amazon.in/gp/product/B08S6XQFDM/ref=ppx_yo_dt_b_asin_title_o00_s00', 'ie=UTF8', 'psc=1•', 'Mag-Safe', 'Magnetic', 'Phone', 'Holder', 'Leather', 'Pad', '//www.amazon.in/gp/product/B08RDX7GZ5/ref=ppx_yo_dt_b_asin_title_o00_s00', 'ie=UTF8', 'psc=1', 'Creating', 'collage', 'stuff', 'reference', '11.11.2021', 'Also', 'added', 'arsenal', '•', 'Metal', 'Bumper', '//www.amazon.in/gp/product/B09FZKKPLM/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Magsafe', 'holder', 'Laptop', '//www.amazon.in/gp/product/B095YY319F/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'USB', 'C', 'USB', 'A', '//www.amazon.in/gp/product/B0963ZXFHJ/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Camera', 'Module', 'Guard', '//www.amazon.in/gp/product/B09H36MHF6/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1•', 'Charging', 'Station', '//www.amazon.in/gp/product/B096FNG2MJ/ref=ppx_yo_dt_b_search_asin_title', 'ie=UTF8', 'psc=1', 'That\\', 'folk', '\\n\\n', "'\\n\\n", 'Need', 'camera', 'software', 'update', 'rest', 'fine.\\n\\n', "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0Best', '💙', 'blue', 'colour', 'awesome', '..', 'BEAST', '💙🍎\\n\\n', '``', '\\n\\n', 'According', 'guysFirst', 'purchased', 'iPhoneSecondly', 'budget', '1lakhs', 'spending', 'worth', 'allInfact', 'invest', 'money', 'stock', 'stock', 'money', 'doubled', 'future', 'bcoz', 'buying', 'depreciating', 'assetHope', 'understand', '🙂\\n\\n', "''", "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0The', 'excellent', 'Samsung', 'galaxy', '21', 'ultra', 'macro', 'photography', 'After', 'announced', 'macro', 'photography', 'ability', 'decided', 'blindfoldedly', 'delivery', 'delayed', 'demand', 'supply', 'difference', 'worth', 'wait', 'thing', 'glass', 'shield', 'cover', 'thought', 'kill', 'nice', 'iOS', 'Simple', 'settings.\\n\\n', '``', '\\n\\n', 'previously', 'owned', '12', 'Pro', 'shifted', '13', 'boy', 'disappointed', 'What', 'loved', 'camera', 'pic', 'attached', 'night', 'photography', 'pic', 'uploaded', 'shot', '7', 'pm', 'Apart', 'camera', 'refresh', 'rate', 'scrolling', 'supported', 'apps', 'giving', 'lag', 'input', 'Overall', 'choose', 'smartphone', 'super', 'money', 'spent', 'cost', 'it.\\n\\n', "''", "'\\n\\n", 'With', 'incremental', 'improvement', 'area', 'matter', 'camera', 'display', 'beast', 'iPhone.\\n\\n', "'\\n\\n", 'Well', 'switched', 'One', 'Now', 'fact', 'dream', 'So', 'bought', 'Everything', 'marvellous', '..', 'technical', 'review', 'write', 'again…', 'Comparing', 'io', 'sense', 'completely', 'platform', 'purpose', 'Various', 'people', 'gave', 'review', 'comparing', 'practical…', 'understand', 'money', '..', 'wont', 'regret\\n\\n', "'\\n\\n", 'This', 'earlier', 'iPhones', '’', 'backup', '13', 'max', 'completely', 'changed', 'view', 'feel', 'aspects.\\n\\n', "'\\n\\n", 'It', 'elevates', 'great', 'Iphone', 'experience', 'motion', 'display', 'excellent', 'camera', '\\n\\n', '``', '\\n\\n\\n\\n\\n', 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0I', 'switched', '11', 'max', '13', 'max', 'As', 'experience', 'simple', 'Yes', 'expensive', 'sight', 'set', 'buy.Pros', 'Display', 'gorgeous', '120Hz', 'Premium', 'delivers', 'it.', 'Battery', 'life', 'unbelievable', 'drain', 'single', 'ending', '30~35', 'end', 'Build', 'quality', 'unquestionably', 'Solid', 'Beautiful.', 'New', 'camera', 'setup', 'phone', 'andunquestionably', 'Video', 'recording', 'usual', 'Finally', '3x', 'zoom', 'make', 'zoom', 'scene', 'past', 'iPhones', 'Flat', 'help', 'applying', 'protector', 'general.', 'Performance', 'Smartphone', 'lag', 'hiccup', 'gameplay', 'time.Cons', 'Price', 'Yes', 'extremely', 'expensive', 'India', 'Flagships', 'Samsung', 'touched', 'price', 'factor', 'about.', 'Heaviest', '240', 'gram', 'lot', 'weight', 'mean', 'build', 'solid', 'huge', 'too.', 'Unconventional', 'dual', 'sim', 'style', 'Physical', 'SIM', 'eSIM', 'issue', 'user', '2', 'physical', 'SIM', 'cards.', 'Usual', 'limitation', 'iOS', 'lime', 'lack', 'customisation', 'Android', 'user', 'love', 'point', 'limitation', 'deal', 'breakers.\\n\\n', "''", '``', '\\n\\n', 'skeptical', 'genuineness', 'receive', 'stock', 'store', 'So', 'brought', 'gut', 'feeling', 'purchase', 'delivered', 'When', 'opened', 'box', 'strikingly', 'beautiful', 'checked', 'authenticity', 'verifying', 'way', 'Now', 'importantly', 'genuine', '13', 'max', 'hand', 'It', 'work', 'great', 'longer', 'life', 'previous', 'phone', 'had.\\n\\n', "''", "'\\n\\n", 'Great', 'Product', 'Worth', 'buying', 'Amazon', 'Delivery', 'Great', '\\n\\n', "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0From', '6S', '2015', '13', 'max', '2021', 'thing', 'remains', '’', 'performance', 'oneplus', 'comparison', 'beast', 'From', 'camera', 'gaming', '..', 'notch', 'life', 'superb', 'till', 'Normal', 'usage', 'upto', '3', 'day', 'charge', 'Bought', 'earpods', 'iwatch', 'compliment', 'beast🤭\\n\\n', "'\\n\\n", 'This', 'superbly', 'amazing', 'feature', 'display', 'smooth', 'Camera', 'damn', 'good.\\n\\n', "'\\n\\n", 'Shifting', '8', '64', 'GB', '13', 'Pro', '1', 'TB', 'left', 'Really', 'impressed', 'build', 'quality', 'durability', 'weighs', 'slightly', 'heavier', '12', 'Pro', 'model', 'sister', 'Really', 'satisfied', 'Camera', 'Display', 'Screen', 'brightness', 'Sound', 'quality', 'well.\\n\\n', "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n', '``', '\\n\\n', 'Major', 'point', 'Massive', 'life', 'charge', 'morning', '5:30', '7', 'charged', 'till', 'night', 'charge', '30', 'left', 'Best', 'screen.Best', 'Camera.It', 'fastThat', 'care', 'me.Cons-', 'Expensive.\\n\\n', "''", "'\\n\\n", '1', 'Blue', 'Colour', 'good.2', 'Battery', 'long', 'lasting', 'For', 'usage', '1', 'charge', '2', 'days.3', 'Camera', 'improved', 'There', 'competitor', 'phone', 'lesser', 'camera', 'quality.4', 'Phone', 'heavy', 'days.5', 'Sound', 'quality', 'amazing.6', 'Display', 'But', '’', 'feel', 'difference', '120', 'Hz', 'display', 'older', 'iPhones.7', 'Overall', 'performance', 'good.\\n\\n', "'\\n\\n", 'Trusted', 'seller', '1', 'week', 'unboxed', 'yesterday', 'Well', 'Packed', 'cover', 'ur', 'pocket', 'It', '’', 'Human', 'Made', 'Mobile', 'world', '’', 'costlier', 'industryI', 'switched', 'Samsung', '’', 'hard', 'transfer', 'WhatsApp', 'spent', '’', 'tricky', 'leaved', 'itOthercamera', '5/5', '’', 'competitive', 'fr', 'DSLR', 'mirrorless', 'rangeCall', 'quality', 'display', 'sound', '5/5', 'user', 'appleOverall', 'hope', 'fr', 'yearsJai', 'Hind\\n\\n', "'\\n\\n", 'Well', 'product', 'live', 'expectation', 'factor', 'share', 'view', 'amazing', 'camera', 'great', 'quality', 'feel', 'premium', 'wonderful', 'life', 'lastly', 'multitask', 'performance', 'glitch', '..', '\\n\\n', "'\\n\\n", 'iOS', '15', 'feel', 'silky', 'smooth', '120Hz', 'refresh', 'rate', 'And', 'A15', 'competition.\\n\\n', "'\\n\\n", 'Writing', 'week', 'usage', 'switched', 'Samsung', 'A50', 'light', 'quality', 'happy', 'All', 'review', 'online', 'Pro', 'max', 'bulky', 'Hand', 'pain', 'holding', '10', 'min', 'browsing', 'Though', 'review', 'told', 'overlooked', 'aspect.Think', 'buying', 'It', 'small', 'thing', 'You', '’', 'aspect', 'hand', 'start', 'paining.\\n\\n', "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0Battery', 'quality', 'average', 'stand', '2-3', 'day', 'set', 'money\\n\\n', "'\\n\\n", 'So', 'food', 'chain', 'Worth', 'money.\\n\\n', "'\\n\\n", 'Overall', 'excellent', 'Specially', 'camera', 'screen.\\n\\n', "'\\n\\n", 'One', 'Phone', 'picture', 'quality', 'speed', 'usability', 'display', 'super', 'awesome', 'mobile.\\n\\n', "'\\n\\n", 'Top', 'notch', 'aspect\\n\\n', "'\\n\\n\\n\\n\\n", 'medium', 'loaded.\\n', '\\n\\n\\n\\n\\n', '\\xa0Just', 'excellent', '🙈\\n\\n', "'\\n\\n", 'great', 'experience', 'future', 'sure.\\n\\n', "'\\n\\n", 'Do', 'Price', 'Is', 'High', 'But', 'Product', 'Is', 'True', 'For', 'Money', '.\\n\\n', "'\\n\\n", 'It', '’', 'magical', 'device.\\n\\n', '``', "'\\n\\n", 'Typical', 'Very', 'expensive', 'feel', 'premium', 'respect', '..', '\\n\\n', "'\\n\\n", 'Amazing', 'build', 'quality', 'camera', 'display', 'surround', 'sound\\n\\n', "'\\n\\n", 'Single', 'word', '…', 'Amazing', '\\n\\n', "'\\n\\n", 'Buy', 'store\\n\\n', "'\\n\\n", 'love', 'serria', 'colour\\n\\n', "'\\n\\n", 'Value', 'productUse', 'feel', '😇😇😇\\n\\n', "'\\n\\n", 'Very', 'good\\n\\n', "'\\n\\n", 'Nice', 'product\\n\\n', "'\\n\\n", '12', 'maxx', 'massive', 'powerfull', '13', 'maxx\\n\\n', "'\\n\\n", 'Excellent\\n\\n', "'\\n\\n", 'Damm', 'good\\n\\n', '``', "'\\n\\n", 'Totally', 'worth\\n\\n', "'\\n\\n", '5starAwesome\\n\\n', "'\\n\\n", 'This', 'worth', '1.3', 'lakh', 'Nothing', 'great', 'asks', 'Same', 'notch', 'outdated', 'design', 'charger', 'charger', 'cover', 'guard', 'cost', '5k', 'Only', 'buy', 'dream', 'people', 'giving', '5', 'star', 'dreamt', 'brand', 'tag', 'buying', 'ground', 'breaking', 'technology', 'Any', '60k-50k', 'stuff', 'Chinese', 'brand', '30-40k', 'phone', 'display', 'backup', 'camera', '\\n\\n', '``', '\\n\\n', 'Got', 'launch', 'happy', 'Upgraded', '11', 'max.ProThat', 'camera', 'All', 'camera', 'lens', 'year', 'pretty', 'solid', 'Though', 'portrait', 'mode', 'lens', 'faster', 'Still', 'quality', 'though.The', 'pretty', 'solid', 'year', 'ending', '50-60', 'life.Tried', 'game', 'There', 'heating', 'allThe', 'size', 'Its', 'handed', 'single', 'handed', '12', '13', 'redesign', 'flat', 'edge', 'easier', 'hold', 'comparison', '11', 'You', 'buy', 'case', 'Without', 'case', 'slip', 'hand.ConsNo', 'USB-CIn', 'picture', '11', 'left', '13', 'right.\\n\\n', "''", "'\\n\\n", 'Battery', 'great', 'performance', 'Americans', 'paying', '1599', 'dollar', 'i.e', '119000', 'Rs', 'max', '1TB', 'Indian', 'pay', '179900', 'Rs', 'paying', '60000', 'Rs', 'quaint', 'software', 'customisation', 'disgusting', 'caterpillar', 'notch', 'USB', 'C', 'charger', 'Ridiculous', 'indian', 'fooled', 'brandRelatively', 'vivo', 'x70', 'pro+', 'camera', 'nightmode', 'portrays', 'overpriced', 'junkFinally', 'open', 'assembly', 'factory', 'india', 'eventually', 'obliterated', 'competitionWhy', 'pay', '60K', '....', 'sensible\\n\\n', "'\\n\\n", 'One', '8', 'year', 'sold', '26K', 'thinking', 'money', 'buy', '13', 'max', 'ended', 'buying', 'store', 'So', '6', '3', 'month', 'Even', '6', 'lasted', 'morning', 'evening', 'apps', 'worst', 'waited', 'waited', '13', 'max', 'resist', 'buying', 'launch', 'First', 'gettng', 'life', '2', 'day', 'moderate', 'usage', 'ITs', 'huge', 'leap', 'till', 'And', 'Iphone', 'Android', 'wanted', 'accept', 'Android', 'damn', 'smooth', 'espcially', '120', 'hz', 'noticed', 'paried', 'UAG', 'case', 'SPigen', 'protector', 'lookng', 'damn', 'good.\\n\\n', '``', '\\n\\n', 'undoubtedly', 'changing', 'ugly', 'notch', '4th', 'generation', 'Face', 'unlock', 'mask', 'useless', 'Exta', 'cloud', 'storage', 'extra', 'money', 'additional', 'charge', 'lack', 'memory', 'card', 'pure', 'mark', 'consumerism', 'capitalism', 'Removing', 'charger', 'headphone', 'How', 'person', 'supposed', 'basic', 'necessity', 'With', 'Google', 'adding', 'Samsung', 'powered', 'phone', 'rethink', 'strategy', 'Nokia.\\n\\n', "''", "'\\n\\n", 'Worst', 'bad', 'camera', 'bad', 'life', 'main', 'thing', 'hype', 'created', 'worst', '.\\n\\n', "'\\n\\n", 'Awesome', '😎', 'dream', 'suggest', 'buy', 'Very', 'rate', 'high', 'bessst\\n\\n', "'\\n\\n", 'X', '3', 'year', 'It', 'till', 'bought', '13', '.Mainly', 'camera', 'performance', 'life', 'notice', 'week', '.Night', 'mode', 'And', 'cinematic', 'feature', 'hope', 'perfect', '120', 'HZ', 'refresh', 'rate', '’', 'notice', 'played', 'game', 'But', 'brighter', 'compare', 'X', '.Battery', 'life', 'Getting', '3-4', 'hour', 'X', '.A', 'worthy', 'update', 'X', '.Once', 'thought', 'But', '’', 'comparable', '10', 'It', '’', 'till', 'sep', '2022\\n\\n', '``', '\\n\\n', 'If', 'enjoy', 'iOS', 'Of', 'break', 'bank', '2021', 'If', 'Android', 'Galaxy', 'S21', 'Ultra', 'advise', 'Fold3', 'strange', 'aspect', 'ratio', 'content', 'gaming', 'spreadsheet', 'mail', 'But', 'case', 'permit', 'Fold3', 'fragile', 'gaming', 'session', 'Brawl', 'Stars', 'press', 'hard', 'bump', 'nope', 'that.If', 'camera', '2021', '13', 'Pro/Max', 'S21', 'Ultra', 'If', 'video', 'beat', 'ProRez', 'normal', '4k30', 'video', 'iPhones.Best', '13', 'Pro', 'on-point', 'loudspeaker', 'wide', 'soundstage', 'tiny', 'speaker', 'vibration', 'motor', 'camera', 'video', '2', 'camera', 'still', 'insanely', 'mad', 'bright', '1', 'beta/dev', 'update', 'unlike', 'phone', 'min', '5', 'year', 'assuming', 'long', 'update', 'factor', 'ultra', 'flagship', 'phone', 'Screen', '8-10', 'hour', 'depending', 'usage', 'easily', 'last', '1.5', 'day', 'non-heavy', 'easily', '2', 'days.I', 'rock', 'daily', 'driver', 'primary', '13', 'Pro', 'secondary', 'OP', '7T', 'issue', 'Android', 'fact', '6', 'year', 'secondary', 'limitation', 'gen', 'iOS', 'power', 'user', 'friendly', 'Android.If', 'afford', '13', 'Pro', 'money', 'buy', '\\n\\n', "''", "'\\n\\n", 'Utilitarian', 'philosphers', 'jeremy', 'bentham', 'evolved', 'consequential', 'theory', 'basically', 'focus', 'pleasure', 'happiness', 'pain', 'sadness', 'derived', 'act', 'declaring', 'act', 'moral', 'immoral', 'concept', 'act', 'considered', 'moral', 'derive', 'maximum', 'happiness', 'maximum', 'number', 'people', 'happy', 'applying', 'concept', 'daily', 'life', 'ethical', 'dilemma', 'case', 'pain', 'individual', 'ethical', 'happiness', 'large', 'number', 'people', 'theory', 'simplify', 'choice', 'life', 'purchase', '13', 'max', 'agree', 'jeremy', 'bentham', 'calculate', 'numver', 'people', 'purchase', 'happy.That', 'individual', 'gifting', 'parent', 'max', '2', '3


## Named Entity Recognition(NER)

In chunking, we read that we can set rules to keep different POS tags under one sinlge user defined tag. One such form of chunking in NLP is known as Named Entity Recognition.

In NER, we try to group entities like people, places, countries, things etc. together.

    📌 When and Where to Use NER?
we use NER when you want to extract important information from unstructured text. Some real-life examples:

📘 Use Case	✨ Purpose of NER
📄 Resume parser	Extract names, skills, degrees, institutions
📰 News article analysis	Identify companies, events, people
💼 Market intelligence	Pull out competitors, products, pricing info
🧾 Invoice/data processing	Extract names, dates, amounts
🤖 Chatbots	Understand who/what the user is referring to
🛍️ E-commerce search	Extract product names, brands, categories

In [89]:
lemma_sent = [word.capitalize() for word in lemma_sent]

#1st we pos tagging then name entity recognization

pos_tagged= nltk.pos_tag(lemma_sent)

print(pos_tagged)

# now the next step is name entity from that pos tagged
name_entity=nltk.ne_chunk(pos_tagged,binary=True)
print(name_entity)
#name_entity.draw()

[("'\\n\\n", 'POS'), ('Update', 'NNP'), ('13.121.2021', 'CD'), ('Added', 'NNP'), ('Unnecessary/money-wasting', 'JJ'), ('Accessory', 'NNP'), ('Samsung', 'NNP'), ('Does', 'NNP'), ('Right', 'NNP'), ('So', 'NNP'), ('Switched', 'NNP'), ('Android', 'NNP'), ('Galaxy', 'NNP'), ('Note', 'NNP'), ('User', 'NNP'), ('2015', 'CD'), ('Upgrading', 'NNP'), ('Year', 'NNP'), ('Note', 'NNP'), ('7', 'CD'), ('…the', 'NN'), ('13', 'CD'), ('Pro', 'NNP'), ('Design', 'NNP'), ('Similar', 'NNP'), ('12', 'CD'), ('Pro', 'NNP'), ('—', 'FW'), ('Discernible', 'NNP'), ('Change', 'NNP'), ('Thicker', 'NNP'), ('Camera', 'NNP'), ('Bump', 'NNP'), ('Larger', 'NNP'), ('Square', 'NNP'), ('This', 'DT'), ('Highlight', 'NNP'), ('Significant', 'NNP'), ('Change', 'NNP'), ('Past', 'NNP'), ('Year.on', 'NNP'), ('Display', 'NNP'), ('Notch', 'NNP'), ('Smaller', 'NNP'), ('But', 'CC'), ('Mean', 'NNP'), ('Year', 'NNP'), ('Display', 'NNP'), ('Real', 'NNP'), ('Estate', 'NNP'), ('Fix', 'NNP'), ('Strangely', 'NNP'), ('Felt', 'VBD'), ('13', 'CD'), ('Pro', 'NNP'), ('Weighed', 'VBD'), ('Lot…240', 'NNP'), ('Gram', 'NNP'), ('Will', 'NNP'), ('Run', 'NNP'), ('Spec-sheet', 'NNP'), ('Readily', 'NNP'), ('Online', 'NNP'), ('What', 'WP'), ('’', 'VBD'), ('Let', 'JJ'), ('Thing', 'NNP'), ('Straight', 'NNP'), ('It', 'PRP'), ('Pointless', 'NNP'), ('Talking', 'NNP'), ('Feature', 'NNP'), ('Flagship', 'NNP'), ('They', 'PRP'), ('Expect', 'VBP'), ('Tab', 'NNP'), ('Anticipated', 'NNP'), ('So', 'NNP'), ('Design', 'NNP'), ('Actual', 'NNP'), ('Processing', 'NNP'), ('Power', 'NNP'), ('Top-notch', 'NNP'), ('But', 'CC'), ('Expect', 'NNP'), ('Top-end', 'VBP'), ('A', 'DT'), ('Top-end', 'JJ'), ('Cost', 'NNP'), ('Top-end', 'NNP'), ('Laptop', 'NNP'), ('Company.so', 'NNP'), ('’', 'NNP'), ('Feature', 'NNP'), ('New.•', 'NNP'), ('On', 'IN'), ('13', 'CD'), ('Pro', 'NNP'), ('Literally', 'NNP'), ('Flexing', 'NNP'), ('Camera', 'NNP'), ('Muscle', 'NNP'), ('Big', 'NNP'), ('Bump', 'NNP'), ('Muscle', 'NNP'), ('Lens', 'NNP'), ('Larger', 'NNP'), ('Deeper', 'NNP'), ('Clear', 'NNP'), ('Indication', 'NNP'), ('Camera', 'NNP'), ('Take', 'NNP'), ('Light', 'NNP'), ('Performs', 'NNP'), ('Low', 'NNP'), ('Light.•', 'NNP'), ('All', 'NNP'), ('Translates', 'NNP'), ('Photo', 'NNP'), ('Compared', 'NNP'), ('Generation', 'NNP'), ('Pro', 'NNP'), ('Phone', 'NNP'), ('There', 'EX'), ('Greater', 'NNP'), ('Clarity', 'NNP'), ('Low', 'NNP'), ('Light', 'NNP'), ('Character', 'NNP'), ('Click.•', 'NNP'), ('But', 'CC'), ('’', 'NNP'), ('Sell', 'NNP'), ('For', 'IN'), ('Lined', 'NNP'), ('Macro', 'NNP'), ('Mode', 'NNP'), ('Macro', 'NNP'), ('Mode', 'NNP'), ('Feature', 'NNP'), ('Smartphones', 'NNP'), ('But', 'CC'), ('There', 'EX'), ('Macro', 'NNP'), ('Mode', 'NNP'), ('Camera', 'NNP'), ('App', 'NNP'), ('But', 'CC'), ('Camera', 'NNP'), ('Close', 'NNP'), ('Subject', 'NNP'), ('Switch', 'NNP'), ('Ultra-wide', 'NNP'), ('Lens', 'NNP'), ('Switch', 'NNP'), ('Macro.•', 'NNP'), ('Result', 'NNP'), ('Possibly', 'NNP'), ('Close-up', 'NNP'), ('Shot', 'NNP'), ('Smartphone', 'NNP'), ('But', 'CC'), ('Light', 'NNP'), ('Also', 'RB'), ('Noticed', 'VBD'), ('Image', 'NNP'), ('Sharp', 'NNP'), ('Focal', 'NNP'), ('Point', 'NNP'), ('’', 'NNP'), ('Perfect', 'NNP'), ('’', 'NNP'), ('Shot', 'NNP'), ('Ultra-wide', 'NNP'), ('Lens•', 'NNP'), ('These', 'DT'), ('Day', 'NNP'), ('’', 'NNP'), ('Smartphone', 'NNP'), ('We', 'PRP'), ('Buy', 'NNP'), ('Smartphones', 'NNP'), ('Plethora', 'NNP'), ('Original', 'NNP'), ('Making', 'NNP'), ('Voice', 'NNP'), ('Relegated', 'NNP'), ('Sideline', 'NNP'), ('In', 'IN'), ('Fact', 'NNP'), ('Smartphones', 'NNP'), ('Day', 'NNP'), ('Smart', 'NNP'), ('Powerful', 'NNP'), ('Buy', 'NNP'), ('Device', 'NNP'), ('Primarily', 'NNP'), ('Bothering', 'NNP'), ('Add', 'NNP'), ('Sim', 'NNP'), ('Card', 'NNP'), ('Purchase', 'NNP'), ('There', 'EX'), ('Smartphone', 'NNP'), ('Ability', 'NNP'), ('Push', 'NNP'), ('Limit', 'NNP'), ('Adding', 'NNP'), ('Convenience', 'NNP'), ('Eas', 'NNP'), ('Workflow', 'NNP'), ('13', 'CD'), ('Pro', 'NNP'), ('Aimed', 'NNP'), ('Set', 'NNP'), ('Users.•', 'NNP'), ('Camera', 'NNP'), ('Magic', 'NNP'), ('Notch', 'NNP'), ('Switch', 'NNP'), ('Video', 'NNP'), ('Unleashed', 'NNP'), ('Processing', 'NNP'), ('Power', 'NNP'), ('Tandem', 'NNP'), ('Lens', 'NNP'), ('Computational', 'NNP'), ('Photography', 'NNP'), ('Algorithm', 'NNP'), ('Offer', 'NNP'), ('Cinematic', 'NNP'), ('Mode', 'NNP'), ('This', 'DT'), ('Mode', 'NNP'), ('Thousand', 'NNP'), ('Movie', 'NNP'), ('Scene', 'NNP'), ('’', 'NNP'), ('Trained', 'NNP'), ('Shift', 'NNP'), ('Focus', 'NNP'), ('Subject', 'NNP'), ('Attention', 'NNP'), ('Gaze', 'NNP'), ('Subject', 'NNP'), ('Shift', 'NNP'), ('Doing', 'NNP'), ('Movie', 'NNP'), ('Camera', 'NNP'), ('Tough', 'NNP'), ('Automatically', 'NNP'), ('And', 'CC'), ('’', 'NNP'), ('Change', 'NNP'), ('Editing', 'NNP'), ('Video', 'NNP'), ('Post', 'NNP'), ('Process', 'NNP'), ('All', 'NNP'), ('Mind-boggling', 'NNP'), ('Stuff.there', 'NNP'), ('Weapon', 'NNP'), ('’', 'NNP'), ('Quiver', 'NNP'), ('Prores', 'NNP'), ('Raw', 'NNP'), ('Format', 'NNP'), ('Video.what', 'NNP'), ('Camera', 'NNP'), ('Capability', 'NNP'), ('Viable', 'NNP'), ('Replacement', 'NNP'), ('Lot', 'NNP'), ('Professional', 'NNP'), ('Video', 'NNP'), ('Camera', 'NNP'), ('So', 'NNP'), ('Creator', 'NNP'), ('Video', 'NNP'), ('Camera', 'NNP'), ('Buy', 'NNP'), ('Yes', 'NNP'), ('Camera', 'NNP'), ('Edit', 'NNP'), ('Capture', 'NNP'), ('And', 'CC'), ('Upload', 'NNP'), ('Internet', 'NNP'), ('’', 'NNP'), ('Output', 'NNP'), ('That', 'IN'), ('’', 'NNP'), ('Pro', 'NNP'), ('Start', 'NNP'), ('Making', 'NNP'), ('Sense.it', 'NNP'), ('’', 'NNP'), ('Branding', 'NNP'), ('’', 'NNP'), ('Calling', 'NNP'), ('Card.•', 'NNP'), ('There', 'EX'), ('Set', 'NNP'), ('User', 'NNP'), ('Pro', 'NNP'), ('Inside', 'NNP'), ('Yes', 'NNP'), ('Gamers', 'NNP'), ('Love', 'NNP'), ('Promotion', 'NNP'), ('Adaptive', 'NNP'), ('Refresh', 'NNP'), ('Rate', 'NNP'), ('Again', 'NNP'), ('Thing', 'NNP'), ('Differently', 'NNP'), ('13', 'CD'), ('Pro', 'NNP'), ('Switch', 'NNP'), ('10hz', 'CD'), ('Refresh', 'NNP'), ('Rate', 'NNP'), ('120hz', 'CD'), ('Content', 'NNP'), ('Demand', 'NNP'), ('And', 'CC'), ('’', 'NNP'), ('User', 'NNP'), ('Decide', 'NNP'), ('She', 'PRP'), ('Leave', 'NNP'), ('Complex', 'NNP'), ('Decision-making', 'NNP'), ('A15', 'NNP'), ('Bionic', 'NNP'), ('Power', 'NNP'), ('Phone.•', 'NNP'), ('Frankly', 'NNP'), ('Regular', 'NNP'), ('Stuff', 'NNP'), ('’', 'NNP'), ('Figure', 'NNP'), ('Happening', 'NNP'), ('Display', 'NNP'), ('That', 'IN'), ('’', 'NNP'), ('Smooth', 'NNP'), ('But', 'CC'), ('Start', 'NNP'), ('Playing', 'NNP'), ('Game', 'NNP'), ('Thumper', 'NNP'), ('Pocket', 'NNP'), ('Edition+', 'NNP'), ('Difference', 'NNP'), ('Render', 'NNP'), ('Game', 'NNP'), ('Compared', 'NNP'), ('Earlier', 'NNP'), ('Generation', 'NNP'), ('Remember', 'NNP'), ('Extra', 'NNP'), ('Graphic', 'NNP'), ('Core', 'NNP'), ('Solely', 'NNP'), ('Videos.•', 'NNP'), ('So', 'NNP'), ('Powerful', 'NNP'), ('Well', 'NNP'), ('Powerful', 'NNP'), ('Edit', 'NNP'), ('4k', 'CD'), ('Video', 'NNP'), ('Change', 'NNP'), ('Focus', 'NNP'), ('All', 'NNP'), ('13', 'CD'), ('Pro', 'NNP'), ('Power', 'NNP'), ('Guzzler', 'NNP'), ('Beauty', 'NNP'), ('Offer', 'NNP'), ('Life', 'NNP'), ('This.in', 'NNP'), ('Fact', 'NNP'), ('Review', 'NNP'), ('Period', 'NNP'), ('36', 'CD'), ('Hour', 'NNP'), ('Charging', 'NNP'), ('Upto', 'NNP'), ('100', 'CD'), ('10', 'CD'), ('Left', 'NNP'), ('Crazy', 'NNP'), ('What', 'WP'), ('’', 'VBD'), ('•', 'JJ'), ('``', '``'), ('Tax', 'NNP'), ("''", "''"), ('That\\', 'NNP'), ('Unscrupulous', 'NNP'), ('Money', 'NNP'), ('Demanded', 'NNP'), ('Apple.•', 'NNP'), ('13', 'CD'), ('Pro', 'NNP'), ('Superb', 'NNP'), ('Pull', 'NNP'), ('Punch', 'NNP'), ('Expecting', 'NNP'), ('Feature', 'NNP'), ('Blow', 'NNP'), ('Mind', 'NNP'), ('Change', 'NNP'), ('Life', 'NNP'), ('Daily', 'NNP'), ('Basis', 'NNP'), ('Cinematic', 'NNP'), ('Mode', 'NNP'), ('Testament', 'NNP'), ('Powerful', 'NNP'), ('Smartphones', 'NNP'), ('’', 'NNP'), ('Feature', 'NNP'), ('’', 'NNP'), ('Regular', 'NNP'), ('People', 'NNP'), ('Of', 'IN'), ('Wedding', 'NNP'), ('Photographer', 'NNP'), ('Creator', 'NNP'), ('Thrilled', 'NNP'), ('Executive', 'NNP'), ('’', 'NNP'), ('Upgrading', 'NNP'), ('Phone.•', 'NNP'), ('In', 'IN'), ('Sense', 'NNP'), ('Improved', 'NNP'), ('Life', 'NNP'), ('Feature', 'NNP'), ('Impact', 'NNP'), ('Number', 'NNP'), ('People', 'NNP'), ('Point', 'NNP'), ('Big', 'NNP'), ('Change', 'NNP'), ('Disruptor', 'NNP'), ('Incremental', 'NNP'), ('And', 'CC'), ('Running', 'VBG'), ('20w', 'CD'), ('Charger.should', 'NNP'), ('Buy', 'NNP'), ('13', 'CD'), ('Pro', 'NNP'), ('But', 'CC'), ('Buy', 'NNP'), ('No', 'NNP'), ('That', 'NNP'), ('’', 'VBZ'), ('Pro', 'NNP'), ('Issue', 'NNP'), ('13', 'CD'), ('Regular', 'NNP'), ('User', 'NNP'), ('Pro', 'NNP'), ('Aimed', 'NNP'), ('Camera', 'NNP'), ('Display', 'NNP'), ('Graphic', 'NNP'), ('Power', 'NNP'), ('If', 'IN'), ('Creator', 'NNP'), ('Developer', 'NNP'), ('Working', 'NNP'), ('Cutting-edge', 'NNP'), ('Apps', 'NNP'), ('Must-have', 'NNP'), ('Regular', 'NNP'), ('People', 'NNP'), ('Buy', 'NNP'), ('World', 'NNP'), ('Ahead', 'NNP'), ('Race', 'NNP'), ('Own.and', 'NNP'), ('Max', 'NNP'), ('Line-up', 'NNP'), ('Punch', 'NNP'), ('Hole', 'NNP'), ('Pocket', 'NNP'), ('Deep', 'NNP'), ('Reach', 'NNP'), ('Kidney', 'NNP'), ('That', 'IN'), ('’', 'NNP'), ('Hurt', 'NNP'), ('“', 'NNP'), ('Filthy-rich', 'NNP'), ('”', 'NNP'), ('Though.didn', 'NNP'), ('’', 'NNP'), ('Spam', 'NNP'), ('Gallery', 'NNP'), ('“', 'NNP'), ('Unboxing', 'NNP'), ('”', 'NNP'), ('“', 'NNP'), ('Swiveling', 'NNP'), ('”', 'NNP'), ('“', 'NNP'), ('Showing-off', 'NNP'), ('”', 'NNP'), ('Phone…as', 'NNP'), ('User', 'NNP'), ('Accessories', 'NNP'), ('However', 'RB'), ('’', 'VBD'), ('Attaching', 'NNP'), ('Image', 'NNP'), ('Accessory', 'NNP'), ('Bundled', 'NNP'), ('Left', 'NNP'), ('Transit', 'NNP'), ('Also', 'RB'), ('Linking', 'VBG'), ('Check', 'NNP'), ('•', 'NNP'), ('Usb', 'NNP'), ('3.0', 'CD'), ('Otg', 'NNP'), ('Adapter', 'NNP'), ('Cable', 'NNP'), ('//www.amazon.in/gp/product/b097jqn64t/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Spigen', 'NNP'), ('Smart', 'NNP'), ('Fold', 'NNP'), ('Magnetic', 'NNP'), ('Wallet', 'NNP'), ('Card', 'NNP'), ('Holder', 'NNP'), ('Designed', 'NNP'), ('Magsafe', 'NNP'), ('Kickstand', 'NNP'), ('//www.amazon.in/gp/product/b08s1xm54d/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Usb-c', 'NNP'), ('Lightning', 'NNP'), ('Cable', 'NNP'), ('20', 'CD'), ('Cm', 'NNP'), ('Mfi-certified', 'NNP'), ('Pd', 'NNP'), ('Fast', 'NNP'), ('Charging', 'NNP'), ('Cable', 'NNP'), ('//www.amazon.in/gp/product/b07wvxgfcj/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('0.5', 'CD'), ('Feet', 'NNP'), ('Short', 'NNP'), ('Lightning', 'NNP'), ('Usb', 'NNP'), ('Data', 'NNP'), ('Sync', 'NNP'), ('Cable', 'NNP'), ('Mfi', 'NNP'), ('Certified', 'NNP'), ('//www.amazon.in/gp/product/b01fcujcla/ref=ppx_od_dt_b_asin_title_s00', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Magnetic', 'NNP'), ('Compatible', 'NNP'), ('Case', 'NNP'), ('Back', 'NNP'), ('Cover', 'NNP'), ('Magnetic', 'NNP'), ('Wireless', 'NNP'), ('Charging', 'NNP'), ('Anti-fingerprint', 'NNP'), ('Shockproof', 'NNP'), ('Bumper', 'NNP'), ('//www.amazon.in/gp/product/b09crvqch5/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Denim', 'NNP'), ('Flip', 'NNP'), ('Cover', 'NNP'), ('Premium', 'NNP'), ('Luxury', 'NNP'), ('Slim', 'NNP'), ('Wallet', 'NNP'), ('Folio', 'NNP'), ('Case', 'NNP'), ('Magnetic', 'NNP'), ('Cover', 'NNP'), ('//www.amazon.in/gp/product/b094fhn47q/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Privacy', 'NNP'), ('Tempered', 'NNP'), ('Glass', 'NNP'), ('Screen', 'NNP'), ('Protector', 'NNP'), ('//www.amazon.in/gp/product/b09gbp2nxx/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1', 'NNP'), ('Image', 'NNP'), ('Bought', 'NNP'), ('•', 'NNP'), ('Magnetic', 'NNP'), ('Wireless', 'NNP'), ('Charging', 'NNP'), ('Conversion', 'NNP'), ('Kit', 'NNP'), ('//www.amazon.in/gp/product/b08s6xqfdm/ref=ppx_yo_dt_b_asin_title_o00_s00', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Mag-safe', 'NNP'), ('Magnetic', 'NNP'), ('Phone', 'NNP'), ('Holder', 'NNP'), ('Leather', 'NNP'), ('Pad', 'NNP'), ('//www.amazon.in/gp/product/b08rdx7gz5/ref=ppx_yo_dt_b_asin_title_o00_s00', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1', 'NNP'), ('Creating', 'NNP'), ('Collage', 'NNP'), ('Stuff', 'NNP'), ('Reference', 'NNP'), ('11.11.2021', 'CD'), ('Also', 'RB'), ('Added', 'NNP'), ('Arsenal', 'NNP'), ('•', 'NNP'), ('Metal', 'NNP'), ('Bumper', 'NNP'), ('//www.amazon.in/gp/product/b09fzkkplm/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Magsafe', 'NNP'), ('Holder', 'NNP'), ('Laptop', 'NNP'), ('//www.amazon.in/gp/product/b095yy319f/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Usb', 'NNP'), ('C', 'NNP'), ('Usb', 'NNP'), ('A', 'NNP'), ('//www.amazon.in/gp/product/b0963zxfhj/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Camera', 'NNP'), ('Module', 'NNP'), ('Guard', 'NNP'), ('//www.amazon.in/gp/product/b09h36mhf6/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1•', 'NNP'), ('Charging', 'NNP'), ('Station', 'NNP'), ('//www.amazon.in/gp/product/b096fng2mj/ref=ppx_yo_dt_b_search_asin_title', 'NNP'), ('Ie=utf8', 'NNP'), ('Psc=1', 'NNP'), ('That\\', 'NNP'), ('Folk', 'NNP'), ('\\n\\n', 'NNP'), ("'\\n\\n", 'POS'), ('Need', 'NNP'), ('Camera', 'NNP'), ('Software', 'NNP'), ('Update', 'NNP'), ('Rest', 'NNP'), ('Fine.\\n\\n', 'NNP'), ("'\\n\\n\\n\\n\\n", 'POS'), ('Medium', 'NNP'), ('Loaded.\\n', 'NNP'), ('\\n\\n\\n\\n\\n', 'NNP'), ('\\xa0best', 'NNP'), ('💙', 'NNP'), ('Blue', 'NNP'), ('Colour', 'NNP'), ('Awesome', 'NNP'), ('..', 'NNP'), ('Beast', 'NNP'), ('💙🍎\\n\\n', 'NNP'), ('``', '``'), ('\\n\\n', 'NNP'), ('According', 'VBG'), ('Guysfirst', 'NNP'), ('Purchased', 'VBD'), ('Iphonesecondly', 'NNP'), ('Budget', 'NNP'), ('1lakhs', 'CD'), ('Spending', 'NNP'), ('Worth', 'NNP'), ('Allinfact', 'NNP'), ('Invest', 'NNP'), ('Money', 'NNP'), ('Stock', 'NNP'), ('Stock', 'NNP'), ('Money', 'NNP'), ('Doubled', 'NNP'), ('Future', 'NNP'), ('Bcoz', 'NNP'), ('Buying', 'NNP'), ('Depreciating', 'NNP'), ('Assethope', 'NNP'), ('Understand', 'NNP'), ('🙂\\n\\n', 'NNP'), ("''", "''"), ("'\\n\\n\\n\\n\\n", 'POS'), ('Medium', 'NNP'), ('Loaded.\\n', 'NNP'), ('\\n\\n\\n\\n\\n', 'NNP'), ('\\xa0the', 'NNP'), ('Excellent', 'NNP'), ('Samsung', 'NNP'), ('Galaxy', 'NNP'), ('21', 'CD'), ('Ultra', 'NNP'), ('Macro', 'NNP'), ('Photography', 'NNP'), ('After', 'IN'), ('Announced', 'NNP'), ('Macro', 'NNP'), ('Photography', 'NNP'), ('Ability', 'NNP'), ('Decided', 'VBD'), ('Blindfoldedly', 'RB'), ('Delivery', 'NNP'), ('Delayed', 'NNP'), ('Demand', 'NNP'), ('Supply', 'NNP'), ('Difference', 'NNP'), ('Worth', 'NNP'), ('Wait', 'NNP'), ('Thing', 'NNP'), ('Glass', 'NNP'), ('Shield', 'NNP'), ('Cover', 'NNP'), ('Thought', 'NNP'), ('Kill', 'NNP'), ('Nice', 'NNP'), ('Ios', 'NNP'), ('Simple', 'NNP'), ('Settings.\\n\\n', 'NNP'), ('``', '``'), ('\\n\\n', 'NNP'), ('Previously', 'NNP'), ('Owned', 'VBD'), ('12', 'CD'), ('Pro', 'NNP'), ('Shifted', 'VBD'), ('13', 'CD'), ('Boy', 'NNP'), ('Disappointed', 'VBD'), ('What', 'WP'), ('Loved', 'NNP'), ('Camera', 'NNP'), ('Pic', 'NNP'), ('Attached', 'NNP'), ('Night', 'NNP'), ('Photography', 'NNP'), ('Pic', 'NNP'), ('Uploaded', 'NNP'), ('Shot', 'NNP'), ('7', 'CD'), ('Pm', 'NNP'), ('Apart', 'NNP'), ('Camera', 'NNP'), ('Refresh', 'NNP'), ('Rate', 'NNP'), ('Scrolling', 'NNP'), ('Supported', 'NNP'), ('Apps', 'NNP'), ('Giving', 'NNP'), ('Lag', 'NNP'), ('Input', 'NNP'), ('Overall', 'NNP'), ('Choose', 'NNP'), ('Smartphone', 'NNP'), ('Super', 'NNP'), ('Money', 'NNP'), ('Spent', 'NNP'), ('Cost', 'NNP'), ('It.\\n\\n', 'NNP'), ("''", "''"), ("'\\n\\n", 'NN'), ('With', 'IN'), ('Incremental', 'NNP'), ('Improvement', 'NNP'), ('Area', 'NNP'), ('Matter', 'NNP'), ('Camera', 'NNP'), ('Display', 'NNP'), ('Beast', 'NNP'), ('Iphone.\\n\\n', 'NNP'), ("'\\n\\n", 'POS'), ('Well', 'NNP'), ('Switched', 'NNP'), ('One', 'CD'), ('Now', 'RB'), ('Fact', 'NNP'), ('Dream', 'NNP'), ('So', 'NNP'), ('Bought', 'NNP'), ('Everything', 'NNP'), ('Marvellous', 'NNP'), ('..', 'NNP'), ('Technical', 'NNP'), ('Review', 'NNP'), ('Write', 'NNP'), ('Again…', 'NNP'), ('Comparing', 'NNP'), ('Io', 'NNP'), ('Sense', 'NNP'), ('Completely', 'RB'), ('Platform', 'NNP'), ('Purpose', 'NNP'), ('Various', 'NNP'), ('People', 'NNP'), ('Gave', 'NNP'), ('Review', 'NNP'), ('Comparing', 'NNP'), ('Practical…', 'NNP'), ('Understand', 'NNP'), ('Money', 'NNP'), ('..', 'NNP'), ('Wont', 'NNP'), ('Regret\\n\\n', 'NNP'), ("'\\n\\n", 'POS'), ('This', 'DT'), ('Earlier', 'NNP'), ('Iphones', 'NNP'), ('’', 'NNP'), ('Backup', 'NNP'), ('13', 'CD'), ('Max', 'NNP'), ('Completely', 'RB'), ('Changed', 'VBD'), ('View', 'NNP'), ('Feel', 'NNP'), ('Aspects.\\n\\n', 'NNP'), ("'\\n\\n", 'POS'), ('It', 'PRP'), ('Elevates', 'VBZ'), ('Great', 'NNP'), ('Iphone', 'NNP'), ('Experience', 'NNP'), ('Motion', 'NNP'), ('Display', 'NNP'), ('Excellent', 'NNP'), ('Camera', 'NNP'), ('\\n\\n', 'VBZ'), ('``', '``'), ('\\n\\n\\n\\n\\n', 'JJ'), ('Medium', 'NNP'), ('Loaded.\\n', 'NNP'), ('\\n\\n\\n\\n\\n', 'NNP'), ('\\xa0i', 'NNP'), ('Switched', 'VBD'), ('11', 'CD'), ('Max', 'NNP'), ('13', 'CD'), ('Max', 'NNP'), ('As', 'IN'), ('Experience', 'NNP'), ('Simple', 'NNP'), ('Yes', 'NNP'), ('Expensive', 'NNP'), ('Sight', 'NNP'), ('Set', 'NNP'), ('Buy.pros', 'NNP'), ('Display', 'NNP'), ('Gorgeous', 'NNP'), ('120hz', 'CD'), ('Premium', 'NNP'), ('Delivers', 'NNP'), ('It.', 'NNP'), ('Battery', 'NNP'), ('Life', 'NNP'), ('Unbelievable', 'NNP'), ('Drain', 'NNP'), ('Single', 'NNP'), ('Ending', 'NNP'), ('30~35', 'CD'), ('End', 'NNP'), ('Build', 'NNP'), ('Quality', 'NNP'), ('Unquestionably', 'NNP'), ('Solid', 'NNP'), ('Beautiful.', 'NNP'), ('New', 'NNP'), ('Camera', 'NNP'), ('Setup', 'NNP'), ('Phone', 'NNP'), ('Andunquestionably', 'NNP'), ('Video', 'NNP'), ('Recording', 'NNP'), ('Usual', 'NNP'), ('Finally', 'NNP'), ('3x', 'CD'), ('Zoom', 'NNP'), ('Make', 'NNP'), ('Zoom', 'NNP'), ('Scene', 'NNP'), ('Past', 'NNP'), ('Iphones', 'NNP'), ('Flat', 'NNP'), ('Help', 'NNP'), ('Applying', 'NNP'), ('Protector', 'NNP'), ('General.', 'NNP'), ('Performance', 'NNP'), ('Smartphone', 'NNP'), ('Lag', 'NNP'), ('Hiccup', 'NNP'), ('Gameplay', 'NNP'), ('Time.cons', 'NNP'), ('Price', 'NNP'), ('Yes', 'NNP'), ('Extremely', 'NNP'), ('Expensive', 'NNP'), ('India', 'NNP'), ('Flagships', 'NNP'), ('Samsung', 'NNP'), ('Touched', 'NNP'), ('Price', 'NNP'), ('Factor', 'NNP'), ('About.', 'NNP'), ('Heaviest', 'NNP'), ('240', 'CD'), ('Gram', 'NNP'), ('Lot', 'NNP'), ('Weight', 'NNP'), ('Mean', 'NNP'), ('Build', 'NNP'), ('Solid', 'NNP'), ('Huge', 'NNP'), ('Too.', 'NNP'), ('Unconventional', 'NNP'), ('Dual', 'NNP'), ('Sim', 'NNP'), ('Style', 'NNP'), ('Physical', 'NNP'), ('Sim', 'NNP'), ('Esim', 'NNP'), ('Issue', 'NNP'), ('User', 'NNP'), ('2', 'CD'), ('Physical', 'NNP'), ('Sim', 'NNP'), ('Cards.', 'NNP'), ('Usual', 'NNP'), ('Limitation', 'NNP'), ('Ios', 'NNP'), ('Lime', 'NNP'), ('Lack', 'NNP'), ('Customisation', 'NNP'), ('Android', 'NNP'), ('User', 'NNP'), ('Love', 'NNP'), ('Point', 'NNP'), ('Limitation', 'NNP'), ('Deal', 'NNP'), ('Breakers.\\n\\n', 'NNP'), ("''", "''"), ('``', '``'), ('\\n\\n', 'NNP'), ('Skeptical', 'NNP'), ('Genuineness', 'NNP'), ('Receive', 'NNP'), ('Stock', 'NNP'), ('Store', 'NNP'), ('So', 'NNP'), ('Brought', 'NNP'), ('Gut', 'NNP'), ('Feeling', 'NNP'), ('Purchase', 'NNP'), ('Delivered', 'NNP'), ('When', 'WRB'), ('Opened', 'VBN'), ('Box', 'NNP'), ('Strikingly', 'NNP'), ('Beautiful', 'NNP'), ('Checked', 'NNP'), ('Authenticity', 'NNP'), ('Verifying', 'NNP'), ('Way', 'NNP'), ('Now', 'RB'), ('Importantly', 'RB'), ('Genuine', 'NNP'), ('13', 'CD'), ('Max', 'NNP'), ('Hand', 'NNP'), ('It', 'PRP'), ('Work', 'NNP'), ('Great', 'NNP'), ('Longer', 'NNP'), ('Life', 'NNP'), ('Previous', 'NNP'), ('Phone', 'NNP'), ('Had.\\n\\n', 'NNP'), ("''", "''"), ("'\\n\\n", 'POS'), ('Great', 'NNP'), ('Product', 'NNP'), ('Worth', 'NNP'), ('Buying', 'NNP'), ('Amazon', 'NNP'), ('De

In [127]:
import nltk
from nltk.tree import Tree # Important to import Tree for type checking

text = "Barack Obama met with Angela Merkel in Berlin. John Doe works at Google."

words = nltk.word_tokenize(text)

tagged_words = nltk.pos_tag(words)

# --- Perform Named Entity Recognition (NER) chunking ---

name_entity = nltk.ne_chunk(tagged_words, binary=False)

# --- Step 5: Extract PERSON names from the chunked entities ---
person_names = [] 

# Iterate through each item in the 'name_entity' structure.
# Each item can be either a Tree (if it's a recognized entity like PERSON)
# or a simple (word, pos_tag) tuple (if it's not a recognized entity).
for subtree in name_entity:
    # Check if the current item is an NLTK Tree object
    # AND if its label (the type of entity) is 'PERSON'
    if isinstance(subtree, Tree) and subtree.label() == 'PERSON':
        # If it's a PERSON entity, extract the words that make up the name.
        # subtree.leaves() returns a list of (token, pos) tuples for the words in this entity.
        # We only want the 'token' (the word itself), not the 'pos' tag.
        tokens = []
        for token, pos in subtree.leaves():
            tokens.append(token) # Append only the word (token)

        # Join the extracted words to form the full name (e.g., ['Barack', 'Obama'] -> "Barack Obama")
        name = " ".join(tokens)

        # Add the full name to our list of person names
        person_names.append(name)

# --- Step 6: Print the extracted person names ---
print("Extracted Person Names:")
print("Person names:", person_names)
print("Total names:", len(person_names))
print("Unique names:", len(set(person_names)))

Extracted Person Names:
Person names: ['Barack', 'Obama', 'Angela Merkel', 'John Doe']
Total names: 4
Unique names: 4

In [94]:
import nltk
from nltk import pos_tag, word_tokenize, RegexpParser

#nltk.download('punkt')
#nltk.download('averaged_perceptron_tagger')

sentence = "The quick brown fox jumps over the lazy dog"
tokens = word_tokenize(sentence)
pos_tags = pos_tag(tokens)

# Define a grammar rule for noun phrases (NP)
grammar = "NP: {<DT>?<JJ>*<NN>}"

# Create a chunk parser
cp = RegexpParser(grammar)
result = cp.parse(pos_tags)

print(result)
#result.draw()  # Visualize

# Word Vectorization (also called Word Embedding) is a technique in NLP where words are converted into numbers (vectors), so that machine learning models can understand and work with them.


Word Vectorization (Big umbrella term)
This means:
👉 Turning words into numbers so machine learning models can use them.

All  (Count Vectorizer, Word Embedding) are types of word vectorization.


# Count Vectorization (Type of Word Vectorization)
    Bag of Words (BoW) = (Idea + technique using CountVectorizer) word occurrence into no
    This is a concept: represent text by counting words
    
    It uses Count Vectorizer under the hood

So CountVectorizer = tool, BoW = method/concept

CountVectorizer() by default:

Converts all text to lowercase

Removes English stop words if you explicitly tell it to (but not by default)

Ignores single-character words by default 



# Word Embedding (Advanced Word Vectorization)
    This is a smarter technique.
    
    It gives each word a dense vector (list of floats) that captures meaning and context.
    
    📘 Examples:
    
    Word2Vec
    
    GloVe
    
    FastText
    
    Embedding layer in neural networks

Key Methods/Terms
Word vectorizer      &    word embedding

- One-Hot Encoding	- Word2Vec (Skip-gram, CBOW)
- Bag-of-Words (BoW)	- GloVe
- CountVectorizer (Scikit-learn implementation of BoW)	- FastText (incorporates character n-grams)
- TF-IDF (Term Frequency-Inverse Document Frequency)	- Contextual Embeddings (ELMo, BERT, GPT, RoBERTa, etc.)
- HashingVectorizer	- Transformer Models (underlying architecture for BERT, GPT)
- Vocabulary	- Neural Networks (often used for training)
- Corpus	- Distributional Hypothesis (words in similar contexts have similar meanings)

## Word Vectorization (Word Embedding)

Word vectorization is the process of mapping words to a set of real numbers or vectors. This is done to process the given words using machine learning techniques and extract relevant information from them such that it can be used in further predicting words. Vectorization is done by comparing a given word to the corpus(collection) of the available words.
There are many different methods used for vectorizing a given set of words. let's see some of the mosed popular ones:

### Count Vectorizer

Count vectorizer uses two of the following models as the base to vectorize the given words on the basis of frequency of words.

#### Bag of Words Model
BOW model is used in NLP to represent the given text/sentence/document as a collection (bag) of words without giving any importance to grammar or the occurrence order of the words. It keeps the account of frequency of the words in the text document, which can be used as features in many models.

Let’s understand this with an example:

Text1 = “I went to have a cup of coffee but I ended up having lunch with her.”

Text2 = “I don’t understand, what is the problem here?”

BOW1 = {I :2, went : 1, to : 1,have : 1, a : 1, cup: 1, of :1, coffee : 1, but :1, ended : 1, up :1,having : 1, with :1, her :1}

BOW2 = {I : 1, don’t : 1, understand:1, what : 1 , is :1, the : 1, problem : 1, here : 1}

BOW is mainly used for feature selection. The above dictionary is converted as a list with only the frequency terms there and on that basis, weights are given to the most occurring terms. But the “stop words” are the most frequent words that appears in raw document. Thus, having a word with high frequency count doesn’t mean that the word is as important. To resolve this problem, “Tf-idf” was introduced. We will discuss about it later.

#### n-gram model

As discussed in bag of words model, BOW model doesn’t keep the sequence of words in a given text, only the frequency of words matters. It doesn’t take into account the context of the given sentence, or care for grammatical rules such as verb is following a proper noun in the given text.n-gram model is used in such cases to keep the context of the given text intact. N-gram is the sequence of n words from a given text/document.

When, n= 1, we call it a “unigram”.

             n=2, it is called a “bigram”. 
             
             n=3, it is called a “trigram”.
And so on.

Let’s understand this with an example:

Text1 = “I went to have a cup of coffee but I ended up having lunch with her.”

* Unigram 

[I, went, to, have, a, cup, of, coffee, but, I, ended, up, having, lunch, with, her]

* Bi-gram

[I went], [went to],[to have],[have a],[a cup],[cup f],[of coffee],[coffee but],[but I],[I ended],[ended up],
[up having],[having lunch],[lunch with],[with her]

* Tri-gram

[I went to], [went to have], [to have a], [have a cup],[ a cup of], [cup of coffee],[ of coffee but],[ coffee but I],[but I ended],[I ended up],[ended up having],[up having lunch],[having lunch with],[lunch with her].

Note: We can clearly see that BOW model is nothing but n-gram model when n=1.

Skip-grams

Skip grams are type of n-grams where the words are not necessarily in the same order as are in the given text i.e. some words can be skipped. 
Example:

Text2 = “I don’t understand, what is the problem here?”

1-skip 2-grams (we have to make 2-gram while skipping 1 word)

[I understand, don’t what, understand is, what the, is problem, the here].


Let's see the implementation of Count vectorizer in python:

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

docs = ["I love NLP", "NLP is fun"]
vec = CountVectorizer()
bow_matrix = vec.fit_transform(docs).todense()

# Correct way to assign column names
feature_names = vec.get_feature_names_out()
bow_df = pd.DataFrame(bow_matrix, columns=feature_names)

print(bow_df)

   fun  is  love  nlp
0    0   0     1    1
1    1   1     0    1

# Extracting n-grams
# n-grams can be extracted from 3 different techniques:
# listed below are:
# 1. Custom defined function
# 2. NLTK
# 3. TextBlob

In [3]:
string = ["This is an example of n-gram!"]
vect1 = CountVectorizer(ngram_range=(1,1))
vect1.fit_transform(string)
vect2 = CountVectorizer(ngram_range=(2,2))
vect2.fit_transform(string)
vect3 = CountVectorizer(ngram_range=(3,3))
vect3.fit_transform(string)
vect4 = CountVectorizer(ngram_range=(4,4))
vect4.fit_transform(string)
print("2-gram  :",vect2.get_feature_names_out())
print("3-gram  :",vect3.get_feature_names_out())
print("4-gram  :",vect4.get_feature_names_out())

2-gram  : ['an example' 'example of' 'is an' 'of gram' 'this is']
3-gram  : ['an example of' 'example of gram' 'is an example' 'this is an']
4-gram  : ['an example of gram' 'is an example of' 'this is an example']

In [142]:
from nltk import ngrams
from sklearn.feature_extraction.text import CountVectorizer

# Step 1: Create trigrams from text
tokens = 'The cute little boy is playing with the kitten.'.lower().split()
n=ngrams(tokens,3)

trigrams = list(ngrams(tokens, 3))
#[('the', 'cute', 'little'), ('cute', 'little', 'boy'), ('little', 'boy', 'is'), ('boy', 'is', 'playing'), ('is', 'playing', 'with'), ('playing', 'with', 'the'), ('with', 'the', 'kitten.')]


trigram_strings = [' '.join(gram) for gram in trigrams]

print("Trigram Strings:", trigram_strings)
#['the cute little', 'cute little boy', 'little boy is', 'boy is playing', 'is playing with', 'playing with the', 'with the kitten.']

# Step 2: Use CountVectorizer
vec = CountVectorizer()
bow= pd.DataFrame(vec.fit_transform(trigram_strings).todense())
bow.columns=(vec.vocabulary_)
bow

Trigram Strings: ['the cute little', 'cute little boy', 'little boy is', 'boy is playing', 'is playing with', 'playing with the', 'with the kitten.']

   the  cute  little  boy  is  playing  with  kitten
0    0     1       0    0   1        0     1       0
1    1     1       0    0   1        0     0       0
2    1     0       1    0   1        0     0       0
3    1     0       1    0   0        1     0       0
4    0     0       1    0   0        1     0       1
5    0     0       0    0   0        1     1       1
6    0     0       0    1   0        0     1       1

# =================Bag of word model for top 5 frequent terms===========================

In [143]:
cor=['At least seven Indian pharma companies are working to develop a vaccine against coronavirus',
'the deadly virus that has already infected more than 14 million globally.',
'Bharat Biotech, Indian Immunologicals, are among the domestic pharma firms working on the coronavirus vaccines in India.'
]

In [169]:
from sklearn.feature_extraction.text import CountVectorizer

In [145]:
vec=CountVectorizer(max_features=(5))

In [147]:
bow=pd.DataFrame(vec.fit_transform(cor).todense())
bow.columns=(vec.vocabulary_)
bow

   indian  are  working  coronavirus  the
0       1    1        1            0    1
1       0    0        0            1    0
2       1    1        1            2    1

### Term Frequency
It is simply the frequency in which a word appears in a document in comparison to the total number words in the document. Mathematically given as:

Term frequency = (Number of times a word appears in the document) / (Total number of words in the document)


### Inverse Document Frequency

Term frequency has a disadvantage that it tends to give higher weights to words with higher frequency. In such cases words like ‘a’, ‘the’, ‘in’, ’of’ etc. appears more in the documents than other regular words. Thus, more important words are wrongly given lower weights as their frequency is less.
 To tackle this problem IDF was introduced. IDF decreases the weights of such high frequency terms and increases the weight of terms with rare occurrence. Mathematically it is given as:
 
Inverse Document Frequency = log [(Number of documents)/(Number of documents the word appears in)]   

note: [log has base 2]


*Tf-Idf Score = Term frequency * Inverse Document Frequency*

In [170]:
corpus = ['At least seven Indian pharma companies are working to develop a vaccine against coronavirus',
'the deadly virus that has already infected more than 14 million globally.',
'Bharat Biotech, Indian Immunologicals, are among the domestic pharma firms working on the coronavirus vaccines in India.'
]
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
print(tfidf.fit_transform(corpus).todense())

[[0.         0.30300252 0.         0.         0.23044123 0.30300252
  0.         0.         0.30300252 0.23044123 0.         0.30300252
  0.         0.         0.         0.         0.         0.
  0.         0.23044123 0.         0.30300252 0.         0.
  0.         0.23044123 0.30300252 0.         0.         0.
  0.30300252 0.30300252 0.         0.         0.23044123]
 [0.29388386 0.         0.29388386 0.         0.         0.
  0.         0.         0.         0.         0.29388386 0.
  0.         0.         0.29388386 0.29388386 0.         0.
  0.         0.         0.29388386 0.         0.29388386 0.29388386
  0.         0.         0.         0.29388386 0.29388386 0.22350625
  0.         0.         0.         0.29388386 0.        ]
 [0.         0.         0.         0.25644739 0.19503485 0.
  0.25644739 0.25644739 0.         0.19503485 0.         0.
  0.25644739 0.25644739 0.         0.         0.25644739 0.25644739
  0.25644739 0.19503485 0.         0.         0.         0.
  0.25644739 0.19503485 0.         0.         0.         0.39006971
  0.         0.         0.25644739 0.         0.19503485]]

In [173]:
tfidfdf=pd.DataFrame((tfidf.fit_transform(corpus).todense()))
tfidfdf

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,0.000000,0.303003,0.000000,0.000000,0.230441,0.303003,0.000000,0.000000,0.303003,0.230441,...,0.230441,0.303003,0.000000,0.000000,0.000000,0.303003,0.303003,0.000000,0.000000,0.230441
1,0.293884,0.000000,0.293884,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.293884,0.293884,0.223506,0.000000,0.000000,0.000000,0.293884,0.000000
2,0.000000,0.000000,0.000000,0.256447,0.195035,0.000000,0.256447,0.256447,0.000000,0.195035,...,0.195035,0.000000,0.000000,0.000000,0.390070,0.000000,0.000000,0.256447,0.000000,0.195035

In [177]:
tfidfdf.columns = sorted(tfidf.vocabulary_)
tfidfdf.head()

,14,against,already,among,are,at,bharat,biotech,companies,coronavirus,...,pharma,seven,than,that,the,to,vaccine,vaccines,virus,working
0,0.000000,0.303003,0.000000,0.000000,0.230441,0.303003,0.000000,0.000000,0.303003,0.230441,...,0.230441,0.303003,0.000000,0.000000,0.000000,0.303003,0.303003,0.000000,0.000000,0.230441
1,0.293884,0.000000,0.293884,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.293884,0.293884,0.223506,0.000000,0.000000,0.000000,0.293884,0.000000
2,0.000000,0.000000,0.000000,0.256447,0.195035,0.000000,0.256447,0.256447,0.000000,0.195035,...,0.195035,0.000000,0.000000,0.000000,0.390070,0.000000,0.000000,0.256447,0.000000,0.195035

In [178]:
# TFIDF for top 5 frequent terms using tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_model_small = TfidfVectorizer(max_features=5)
tfidf_df_small = pd.DataFrame(tfidf_model_small.fit_transform(corpus).todense())
tfidf_df_small.columns = sorted(tfidf_model_small.vocabulary_)
tfidf_df_small.head()

        are  coronavirus    indian       the   working
0  0.500000     0.500000  0.500000  0.000000  0.500000
1  0.000000     0.000000  0.000000  1.000000  0.000000
2  0.353553     0.353553  0.353553  0.707107  0.353553